// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { FargateTaskDefinitionV2Args } from "./fargateTaskDefinitionV2";
export type FargateTaskDefinitionV2 = import("./fargateTaskDefinitionV2").FargateTaskDefinitionV2;
export const FargateTaskDefinitionV2: typeof import("./fargateTaskDefinitionV2").FargateTaskDefinitionV2 = null as any;
utilities.lazyLoad(exports, ["FargateTaskDefinitionV2"], () => require("./fargateTaskDefinitionV2"));


// Export enums:
export * from "../../types/enums/experimental/ecs";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "awsx:experimental/ecs:FargateTaskDefinitionV2":
                return new FargateTaskDefinitionV2(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("awsx", "experimental/ecs", _module)
