// Code generated by pulumi-gen-awsx DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloudwatch

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-awsx/sdk/v3/go/awsx/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type LogGroupReference struct {
	Arn    string `pulumi:"arn"`
	Name   string `pulumi:"name"`
	Region string `pulumi:"region"`
}

// LogGroupReferenceInput is an input type that accepts LogGroupReferenceArgs and LogGroupReferenceOutput values.
// You can construct a concrete instance of `LogGroupReferenceInput` via:
//
//	LogGroupReferenceArgs{...}
type LogGroupReferenceInput interface {
	pulumi.Input

	ToLogGroupReferenceOutput() LogGroupReferenceOutput
	ToLogGroupReferenceOutputWithContext(context.Context) LogGroupReferenceOutput
}

type LogGroupReferenceArgs struct {
	Arn    pulumi.StringInput `pulumi:"arn"`
	Name   pulumi.StringInput `pulumi:"name"`
	Region pulumi.StringInput `pulumi:"region"`
}

func (LogGroupReferenceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LogGroupReference)(nil)).Elem()
}

func (i LogGroupReferenceArgs) ToLogGroupReferenceOutput() LogGroupReferenceOutput {
	return i.ToLogGroupReferenceOutputWithContext(context.Background())
}

func (i LogGroupReferenceArgs) ToLogGroupReferenceOutputWithContext(ctx context.Context) LogGroupReferenceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogGroupReferenceOutput)
}

func (i LogGroupReferenceArgs) ToLogGroupReferencePtrOutput() LogGroupReferencePtrOutput {
	return i.ToLogGroupReferencePtrOutputWithContext(context.Background())
}

func (i LogGroupReferenceArgs) ToLogGroupReferencePtrOutputWithContext(ctx context.Context) LogGroupReferencePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogGroupReferenceOutput).ToLogGroupReferencePtrOutputWithContext(ctx)
}

// LogGroupReferencePtrInput is an input type that accepts LogGroupReferenceArgs, LogGroupReferencePtr and LogGroupReferencePtrOutput values.
// You can construct a concrete instance of `LogGroupReferencePtrInput` via:
//
//	        LogGroupReferenceArgs{...}
//
//	or:
//
//	        nil
type LogGroupReferencePtrInput interface {
	pulumi.Input

	ToLogGroupReferencePtrOutput() LogGroupReferencePtrOutput
	ToLogGroupReferencePtrOutputWithContext(context.Context) LogGroupReferencePtrOutput
}

type logGroupReferencePtrType LogGroupReferenceArgs

func LogGroupReferencePtr(v *LogGroupReferenceArgs) LogGroupReferencePtrInput {
	return (*logGroupReferencePtrType)(v)
}

func (*logGroupReferencePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**LogGroupReference)(nil)).Elem()
}

func (i *logGroupReferencePtrType) ToLogGroupReferencePtrOutput() LogGroupReferencePtrOutput {
	return i.ToLogGroupReferencePtrOutputWithContext(context.Background())
}

func (i *logGroupReferencePtrType) ToLogGroupReferencePtrOutputWithContext(ctx context.Context) LogGroupReferencePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogGroupReferencePtrOutput)
}

type LogGroupReferenceOutput struct{ *pulumi.OutputState }

func (LogGroupReferenceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LogGroupReference)(nil)).Elem()
}

func (o LogGroupReferenceOutput) ToLogGroupReferenceOutput() LogGroupReferenceOutput {
	return o
}

func (o LogGroupReferenceOutput) ToLogGroupReferenceOutputWithContext(ctx context.Context) LogGroupReferenceOutput {
	return o
}

func (o LogGroupReferenceOutput) ToLogGroupReferencePtrOutput() LogGroupReferencePtrOutput {
	return o.ToLogGroupReferencePtrOutputWithContext(context.Background())
}

func (o LogGroupReferenceOutput) ToLogGroupReferencePtrOutputWithContext(ctx context.Context) LogGroupReferencePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v LogGroupReference) *LogGroupReference {
		return &v
	}).(LogGroupReferencePtrOutput)
}

func (o LogGroupReferenceOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v LogGroupReference) string { return v.Arn }).(pulumi.StringOutput)
}

func (o LogGroupReferenceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LogGroupReference) string { return v.Name }).(pulumi.StringOutput)
}

func (o LogGroupReferenceOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LogGroupReference) string { return v.Region }).(pulumi.StringOutput)
}

type LogGroupReferencePtrOutput struct{ *pulumi.OutputState }

func (LogGroupReferencePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LogGroupReference)(nil)).Elem()
}

func (o LogGroupReferencePtrOutput) ToLogGroupReferencePtrOutput() LogGroupReferencePtrOutput {
	return o
}

func (o LogGroupReferencePtrOutput) ToLogGroupReferencePtrOutputWithContext(ctx context.Context) LogGroupReferencePtrOutput {
	return o
}

func (o LogGroupReferencePtrOutput) Elem() LogGroupReferenceOutput {
	return o.ApplyT(func(v *LogGroupReference) LogGroupReference {
		if v != nil {
			return *v
		}
		var ret LogGroupReference
		return ret
	}).(LogGroupReferenceOutput)
}

func (o LogGroupReferencePtrOutput) Arn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LogGroupReference) *string {
		if v == nil {
			return nil
		}
		return &v.Arn
	}).(pulumi.StringPtrOutput)
}

func (o LogGroupReferencePtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LogGroupReference) *string {
		if v == nil {
			return nil
		}
		return &v.Name
	}).(pulumi.StringPtrOutput)
}

func (o LogGroupReferencePtrOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LogGroupReference) *string {
		if v == nil {
			return nil
		}
		return &v.Region
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LogGroupReferenceInput)(nil)).Elem(), LogGroupReferenceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogGroupReferencePtrInput)(nil)).Elem(), LogGroupReferenceArgs{})
	pulumi.RegisterOutputType(LogGroupReferenceOutput{})
	pulumi.RegisterOutputType(LogGroupReferencePtrOutput{})
}
