// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsx.Experimental.Ecs.Inputs
{

    public sealed class ContainerRestartPolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the restart policy is enabled.
        /// </summary>
        [Input("enabled")]
        public bool? Enabled { get; set; }

        [Input("ignoredExitCodes")]
        private List<double>? _ignoredExitCodes;

        /// <summary>
        /// Exit codes that do not trigger a restart. Specify at most 50 codes.
        /// 
        /// Default - No ignored exit codes in ECS.
        /// </summary>
        public List<double> IgnoredExitCodes
        {
            get => _ignoredExitCodes ?? (_ignoredExitCodes = new List<double>());
            set => _ignoredExitCodes = value;
        }

        /// <summary>
        /// The minimum time, in seconds, the container must run before it is eligible for a restart.
        /// 
        /// Valid values are from 60 through 1800. A container that exits sooner is not restarted.
        /// 
        /// Default - 300 seconds in ECS.
        /// </summary>
        [Input("restartAttemptPeriod")]
        public double? RestartAttemptPeriod { get; set; }

        public ContainerRestartPolicyArgs()
        {
        }
        public static new ContainerRestartPolicyArgs Empty => new ContainerRestartPolicyArgs();
    }
}
