// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsx.Experimental.Ecs.Inputs
{

    public sealed class ContainerPortRangeArgs : global::Pulumi.ResourceArgs
    {
        [Input("end", required: true)]
        public double End { get; set; }

        [Input("start", required: true)]
        public double Start { get; set; }

        public ContainerPortRangeArgs()
        {
        }
        public static new ContainerPortRangeArgs Empty => new ContainerPortRangeArgs();
    }
}
