// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsx.Experimental.Ecs.Inputs
{

    public sealed class CredentialSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Active Directory authentication mode.
        /// </summary>
        [Input("authenticationMode", required: true)]
        public Pulumi.Awsx.Experimental.Ecs.CredentialSpecAuthenticationMode AuthenticationMode { get; set; }

        /// <summary>
        /// An S3 object that contains the credential specification file.
        /// </summary>
        [Input("s3Bucket")]
        public Inputs.S3BucketCredentialSpecArgs? S3Bucket { get; set; }

        /// <summary>
        /// The ARN of an SSM parameter that contains the credential specification file.
        /// </summary>
        [Input("ssmParameterArn")]
        public Input<string>? SsmParameterArn { get; set; }

        public CredentialSpecArgs()
        {
        }
        public static new CredentialSpecArgs Empty => new CredentialSpecArgs();
    }
}
