// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsx.Experimental.Ecs.Inputs
{

    public sealed class ResourceRequirementArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The type of resource to assign.
        /// </summary>
        [Input("type", required: true)]
        public Pulumi.Awsx.Experimental.Ecs.ResourceRequirementType Type { get; set; }

        /// <summary>
        /// The amount or identifier of the resource to assign.
        /// 
        /// For `GPU`, use the device count or `ALL`; total reservations must fit the instance. For
        /// `NeuronDevice`, use `ALL`; only one container per task can request it, on Managed Instances
        /// only. For `InferenceAccelerator`, use the task definition's accelerator `deviceName`.
        /// 
        /// For more information, see
        /// [value](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ResourceRequirement.html#ECS-Type-ResourceRequirement-value).
        /// </summary>
        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public ResourceRequirementArgs()
        {
        }
        public static new ResourceRequirementArgs Empty => new ResourceRequirementArgs();
    }
}
