provider: awsx
aws: true
major-version: 3
template: generic
buildProviderCmd: "OS=$(1) ARCH=$(2) OUT=$(3) yarn --cwd awsx build"
testProviderCmd: "yarn --cwd awsx test"
renovateCmd: "./scripts/renovate.sh"
runner:
    default: pulumi-ubuntu-8core
    prerequisites: pulumi-ubuntu-8core
env:
    ALT_AWS_ACCESS_KEY_ID: ${{ secrets.ALT_AWS_ACCESS_KEY_ID }}
    ALT_AWS_SECRET_ACCESS_KEY: ${{ secrets.ALT_AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-west-2
    PROVIDER: awsx
    PULUMI_API: https://api.pulumi-staging.io
    PULUMI_ENABLE_RESOURCE_REFERENCES: 1
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
releaseVerification:
    nodejs: examples/vpc/nodejs/default-args
    python: examples/cloudtrail/python
    dotnet: examples/cloudtrail/dotnet
    go: examples/cloudtrail/go
