// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsx.Experimental.Ecs.Outputs
{

    [OutputType]
    public sealed class ContainerDefinitionSystemControl
    {
        /// <summary>
        /// The namespaced kernel parameter name, such as `net.ipv4.tcp_keepalive_time`.
        /// </summary>
        public readonly string? Namespace;
        /// <summary>
        /// The value to assign to the kernel parameter.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private ContainerDefinitionSystemControl(
            string? @namespace,

            string? value)
        {
            Namespace = @namespace;
            Value = value;
        }
    }
}
