// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsx.experimental_ecs.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContainerDefinitionHealthCheckArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContainerDefinitionHealthCheckArgs Empty = new ContainerDefinitionHealthCheckArgs();

    /**
     * The command that determines whether the container is healthy.
     * 
     * Start with `CMD` to run arguments directly or `CMD-SHELL` to use the container&#39;s default shell.
     * An exit code of zero indicates success; any other code indicates failure.
     * 
     * Example: `[&#34;CMD-SHELL&#34;, &#34;curl --fail http://localhost/health || exit 1&#34;]`.
     * 
     */
    @Import(name="command")
    private @Nullable List<String> command;

    /**
     * @return The command that determines whether the container is healthy.
     * 
     * Start with `CMD` to run arguments directly or `CMD-SHELL` to use the container&#39;s default shell.
     * An exit code of zero indicates success; any other code indicates failure.
     * 
     * Example: `[&#34;CMD-SHELL&#34;, &#34;curl --fail http://localhost/health || exit 1&#34;]`.
     * 
     */
    public Optional<List<String>> command() {
        return Optional.ofNullable(this.command);
    }

    /**
     * The time, in seconds, between health checks. Valid values are from 5 through 300.
     * 
     * Default - 30 seconds in ECS.
     * 
     */
    @Import(name="interval")
    private @Nullable Double interval;

    /**
     * @return The time, in seconds, between health checks. Valid values are from 5 through 300.
     * 
     * Default - 30 seconds in ECS.
     * 
     */
    public Optional<Double> interval() {
        return Optional.ofNullable(this.interval);
    }

    /**
     * The number of failed checks before the container is unhealthy. Valid values are from 1 through 10.
     * 
     * Default - 3 in ECS.
     * 
     */
    @Import(name="retries")
    private @Nullable Double retries;

    /**
     * @return The number of failed checks before the container is unhealthy. Valid values are from 1 through 10.
     * 
     * Default - 3 in ECS.
     * 
     */
    public Optional<Double> retries() {
        return Optional.ofNullable(this.retries);
    }

    /**
     * The startup grace period, in seconds, before failed checks count toward the retry limit.
     * 
     * Valid values are from 0 through 300. If a check succeeds during this period, subsequent
     * failures count toward the retry limit.
     * 
     * Default - No startup grace period in ECS.
     * 
     */
    @Import(name="startPeriod")
    private @Nullable Double startPeriod;

    /**
     * @return The startup grace period, in seconds, before failed checks count toward the retry limit.
     * 
     * Valid values are from 0 through 300. If a check succeeds during this period, subsequent
     * failures count toward the retry limit.
     * 
     * Default - No startup grace period in ECS.
     * 
     */
    public Optional<Double> startPeriod() {
        return Optional.ofNullable(this.startPeriod);
    }

    /**
     * The time, in seconds, allowed for a health check to succeed. Valid values are from 2 through 60.
     * 
     * Default - 5 seconds in ECS.
     * 
     */
    @Import(name="timeout")
    private @Nullable Double timeout;

    /**
     * @return The time, in seconds, allowed for a health check to succeed. Valid values are from 2 through 60.
     * 
     * Default - 5 seconds in ECS.
     * 
     */
    public Optional<Double> timeout() {
        return Optional.ofNullable(this.timeout);
    }

    private ContainerDefinitionHealthCheckArgs() {}

    private ContainerDefinitionHealthCheckArgs(ContainerDefinitionHealthCheckArgs $) {
        this.command = $.command;
        this.interval = $.interval;
        this.retries = $.retries;
        this.startPeriod = $.startPeriod;
        this.timeout = $.timeout;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContainerDefinitionHealthCheckArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContainerDefinitionHealthCheckArgs $;

        public Builder() {
            $ = new ContainerDefinitionHealthCheckArgs();
        }

        public Builder(ContainerDefinitionHealthCheckArgs defaults) {
            $ = new ContainerDefinitionHealthCheckArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param command The command that determines whether the container is healthy.
         * 
         * Start with `CMD` to run arguments directly or `CMD-SHELL` to use the container&#39;s default shell.
         * An exit code of zero indicates success; any other code indicates failure.
         * 
         * Example: `[&#34;CMD-SHELL&#34;, &#34;curl --fail http://localhost/health || exit 1&#34;]`.
         * 
         * @return builder
         * 
         */
        public Builder command(@Nullable List<String> command) {
            $.command = command;
            return this;
        }

        /**
         * @param command The command that determines whether the container is healthy.
         * 
         * Start with `CMD` to run arguments directly or `CMD-SHELL` to use the container&#39;s default shell.
         * An exit code of zero indicates success; any other code indicates failure.
         * 
         * Example: `[&#34;CMD-SHELL&#34;, &#34;curl --fail http://localhost/health || exit 1&#34;]`.
         * 
         * @return builder
         * 
         */
        public Builder command(String... command) {
            return command(List.of(command));
        }

        /**
         * @param interval The time, in seconds, between health checks. Valid values are from 5 through 300.
         * 
         * Default - 30 seconds in ECS.
         * 
         * @return builder
         * 
         */
        public Builder interval(@Nullable Double interval) {
            $.interval = interval;
            return this;
        }

        /**
         * @param retries The number of failed checks before the container is unhealthy. Valid values are from 1 through 10.
         * 
         * Default - 3 in ECS.
         * 
         * @return builder
         * 
         */
        public Builder retries(@Nullable Double retries) {
            $.retries = retries;
            return this;
        }

        /**
         * @param startPeriod The startup grace period, in seconds, before failed checks count toward the retry limit.
         * 
         * Valid values are from 0 through 300. If a check succeeds during this period, subsequent
         * failures count toward the retry limit.
         * 
         * Default - No startup grace period in ECS.
         * 
         * @return builder
         * 
         */
        public Builder startPeriod(@Nullable Double startPeriod) {
            $.startPeriod = startPeriod;
            return this;
        }

        /**
         * @param timeout The time, in seconds, allowed for a health check to succeed. Valid values are from 2 through 60.
         * 
         * Default - 5 seconds in ECS.
         * 
         * @return builder
         * 
         */
        public Builder timeout(@Nullable Double timeout) {
            $.timeout = timeout;
            return this;
        }

        public ContainerDefinitionHealthCheckArgs build() {
            return $;
        }
    }

}
