// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsx.experimental_ecs.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Double;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ContainerRestartPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContainerRestartPolicyArgs Empty = new ContainerRestartPolicyArgs();

    /**
     * Whether the restart policy is enabled.
     * 
     */
    @Import(name="enabled")
    private @Nullable Boolean enabled;

    /**
     * @return Whether the restart policy is enabled.
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Exit codes that do not trigger a restart. Specify at most 50 codes.
     * 
     * Default - No ignored exit codes in ECS.
     * 
     */
    @Import(name="ignoredExitCodes")
    private @Nullable List<Double> ignoredExitCodes;

    /**
     * @return Exit codes that do not trigger a restart. Specify at most 50 codes.
     * 
     * Default - No ignored exit codes in ECS.
     * 
     */
    public Optional<List<Double>> ignoredExitCodes() {
        return Optional.ofNullable(this.ignoredExitCodes);
    }

    /**
     * The minimum time, in seconds, the container must run before it is eligible for a restart.
     * 
     * Valid values are from 60 through 1800. A container that exits sooner is not restarted.
     * 
     * Default - 300 seconds in ECS.
     * 
     */
    @Import(name="restartAttemptPeriod")
    private @Nullable Double restartAttemptPeriod;

    /**
     * @return The minimum time, in seconds, the container must run before it is eligible for a restart.
     * 
     * Valid values are from 60 through 1800. A container that exits sooner is not restarted.
     * 
     * Default - 300 seconds in ECS.
     * 
     */
    public Optional<Double> restartAttemptPeriod() {
        return Optional.ofNullable(this.restartAttemptPeriod);
    }

    private ContainerRestartPolicyArgs() {}

    private ContainerRestartPolicyArgs(ContainerRestartPolicyArgs $) {
        this.enabled = $.enabled;
        this.ignoredExitCodes = $.ignoredExitCodes;
        this.restartAttemptPeriod = $.restartAttemptPeriod;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContainerRestartPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContainerRestartPolicyArgs $;

        public Builder() {
            $ = new ContainerRestartPolicyArgs();
        }

        public Builder(ContainerRestartPolicyArgs defaults) {
            $ = new ContainerRestartPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Whether the restart policy is enabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Boolean enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param ignoredExitCodes Exit codes that do not trigger a restart. Specify at most 50 codes.
         * 
         * Default - No ignored exit codes in ECS.
         * 
         * @return builder
         * 
         */
        public Builder ignoredExitCodes(@Nullable List<Double> ignoredExitCodes) {
            $.ignoredExitCodes = ignoredExitCodes;
            return this;
        }

        /**
         * @param ignoredExitCodes Exit codes that do not trigger a restart. Specify at most 50 codes.
         * 
         * Default - No ignored exit codes in ECS.
         * 
         * @return builder
         * 
         */
        public Builder ignoredExitCodes(Double... ignoredExitCodes) {
            return ignoredExitCodes(List.of(ignoredExitCodes));
        }

        /**
         * @param restartAttemptPeriod The minimum time, in seconds, the container must run before it is eligible for a restart.
         * 
         * Valid values are from 60 through 1800. A container that exits sooner is not restarted.
         * 
         * Default - 300 seconds in ECS.
         * 
         * @return builder
         * 
         */
        public Builder restartAttemptPeriod(@Nullable Double restartAttemptPeriod) {
            $.restartAttemptPeriod = restartAttemptPeriod;
            return this;
        }

        public ContainerRestartPolicyArgs build() {
            return $;
        }
    }

}
