// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsx.experimental_ecs.inputs;

import com.pulumi.awsx.experimental_ecs.enums.LogConfigurationLogDriver;
import com.pulumi.awsx.experimental_ecs.inputs.ContainerDefinitionSecretArgs;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogConfigurationArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogConfigurationArgs Empty = new LogConfigurationArgs();

    /**
     * The log driver to use. Fargate supports `awslogs`, `splunk`, and `awsfirelens`.
     * 
     * For more information, see
     * [logDriver](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html#ECS-Type-LogConfiguration-logDriver).
     * 
     */
    @Import(name="logDriver", required=true)
    private LogConfigurationLogDriver logDriver;

    /**
     * @return The log driver to use. Fargate supports `awslogs`, `splunk`, and `awsfirelens`.
     * 
     * For more information, see
     * [logDriver](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html#ECS-Type-LogConfiguration-logDriver).
     * 
     */
    public LogConfigurationLogDriver logDriver() {
        return this.logDriver;
    }

    /**
     * Driver-specific configuration options.
     * 
     * For `awslogs`, specify `awslogs-region` and `awslogs-group`. Fargate also requires
     * `awslogs-stream-prefix`. Creating a log group requires `logs:CreateLogGroup` permission.
     * 
     * The `mode` option controls delivery: `blocking` can block application writes when logging
     * fails; `non-blocking` can lose logs when its buffer fills.
     * 
     * For supported options and defaults, see [log
     * options](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html#ECS-Type-LogConfiguration-options).
     * 
     */
    @Import(name="options")
    private @Nullable Map<String,String> options;

    /**
     * @return Driver-specific configuration options.
     * 
     * For `awslogs`, specify `awslogs-region` and `awslogs-group`. Fargate also requires
     * `awslogs-stream-prefix`. Creating a log group requires `logs:CreateLogGroup` permission.
     * 
     * The `mode` option controls delivery: `blocking` can block application writes when logging
     * fails; `non-blocking` can lose logs when its buffer fills.
     * 
     * For supported options and defaults, see [log
     * options](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html#ECS-Type-LogConfiguration-options).
     * 
     */
    public Optional<Map<String,String>> options() {
        return Optional.ofNullable(this.options);
    }

    /**
     * Secrets to pass as log driver options instead of plaintext values.
     * 
     * For more information, see [sensitive
     * data](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html).
     * 
     */
    @Import(name="secretOptions")
    private @Nullable List<ContainerDefinitionSecretArgs> secretOptions;

    /**
     * @return Secrets to pass as log driver options instead of plaintext values.
     * 
     * For more information, see [sensitive
     * data](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html).
     * 
     */
    public Optional<List<ContainerDefinitionSecretArgs>> secretOptions() {
        return Optional.ofNullable(this.secretOptions);
    }

    private LogConfigurationArgs() {}

    private LogConfigurationArgs(LogConfigurationArgs $) {
        this.logDriver = $.logDriver;
        this.options = $.options;
        this.secretOptions = $.secretOptions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogConfigurationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogConfigurationArgs $;

        public Builder() {
            $ = new LogConfigurationArgs();
        }

        public Builder(LogConfigurationArgs defaults) {
            $ = new LogConfigurationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param logDriver The log driver to use. Fargate supports `awslogs`, `splunk`, and `awsfirelens`.
         * 
         * For more information, see
         * [logDriver](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html#ECS-Type-LogConfiguration-logDriver).
         * 
         * @return builder
         * 
         */
        public Builder logDriver(LogConfigurationLogDriver logDriver) {
            $.logDriver = logDriver;
            return this;
        }

        /**
         * @param options Driver-specific configuration options.
         * 
         * For `awslogs`, specify `awslogs-region` and `awslogs-group`. Fargate also requires
         * `awslogs-stream-prefix`. Creating a log group requires `logs:CreateLogGroup` permission.
         * 
         * The `mode` option controls delivery: `blocking` can block application writes when logging
         * fails; `non-blocking` can lose logs when its buffer fills.
         * 
         * For supported options and defaults, see [log
         * options](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html#ECS-Type-LogConfiguration-options).
         * 
         * @return builder
         * 
         */
        public Builder options(@Nullable Map<String,String> options) {
            $.options = options;
            return this;
        }

        /**
         * @param secretOptions Secrets to pass as log driver options instead of plaintext values.
         * 
         * For more information, see [sensitive
         * data](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html).
         * 
         * @return builder
         * 
         */
        public Builder secretOptions(@Nullable List<ContainerDefinitionSecretArgs> secretOptions) {
            $.secretOptions = secretOptions;
            return this;
        }

        /**
         * @param secretOptions Secrets to pass as log driver options instead of plaintext values.
         * 
         * For more information, see [sensitive
         * data](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html).
         * 
         * @return builder
         * 
         */
        public Builder secretOptions(ContainerDefinitionSecretArgs... secretOptions) {
            return secretOptions(List.of(secretOptions));
        }

        public LogConfigurationArgs build() {
            if ($.logDriver == null) {
                throw new MissingRequiredPropertyException("LogConfigurationArgs", "logDriver");
            }
            return $;
        }
    }

}
