// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsx.experimental_ecs.outputs;

import com.pulumi.awsx.experimental_ecs.enums.ContainerDefinitionVersionConsistency;
import com.pulumi.awsx.experimental_ecs.outputs.ContainerDefinitionDependency;
import com.pulumi.awsx.experimental_ecs.outputs.ContainerDefinitionEnvironmentFile;
import com.pulumi.awsx.experimental_ecs.outputs.ContainerDefinitionHealthCheck;
import com.pulumi.awsx.experimental_ecs.outputs.ContainerDefinitionSecret;
import com.pulumi.awsx.experimental_ecs.outputs.ContainerDefinitionSystemControl;
import com.pulumi.awsx.experimental_ecs.outputs.ContainerDefinitionVolumeFrom;
import com.pulumi.awsx.experimental_ecs.outputs.ContainerRestartPolicy;
import com.pulumi.awsx.experimental_ecs.outputs.FirelensConfiguration;
import com.pulumi.awsx.experimental_ecs.outputs.HostEntry;
import com.pulumi.awsx.experimental_ecs.outputs.KeyValuePair;
import com.pulumi.awsx.experimental_ecs.outputs.LinuxParameters;
import com.pulumi.awsx.experimental_ecs.outputs.LogConfiguration;
import com.pulumi.awsx.experimental_ecs.outputs.MountPoint;
import com.pulumi.awsx.experimental_ecs.outputs.PortMapping;
import com.pulumi.awsx.experimental_ecs.outputs.RepositoryCredentials;
import com.pulumi.awsx.experimental_ecs.outputs.ResourceRequirement;
import com.pulumi.awsx.experimental_ecs.outputs.Ulimit;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ContainerDefinitionArgs {
    /**
     * @return The command passed to the container. Use a separate array item for each argument.
     * 
     * For more information, see
     * [command](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-command).
     * 
     */
    private @Nullable List<String> command;
    /**
     * @return The CPU units reserved for the container. There are 1,024 CPU units per vCPU.
     * 
     * On Linux, this controls relative CPU shares, not a hard limit. On Windows, it is a hard limit.
     * For Fargate, the total container CPU reservation must be below the task CPU value.
     * 
     * For more information, see
     * [cpu](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-cpu).
     * 
     */
    private @Nullable Double cpu;
    /**
     * @return Credential specifications for Active Directory authentication. Specify at most one entry.
     * 
     * Use `credentialspec:ARN` or `credentialspecdomainless:ARN`, with an SSM or S3 ARN. Prefer this
     * property to `dockerSecurityOptions` for credential specifications.
     * 
     * For more information, see
     * [credentialSpecs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-credentialSpecs).
     * 
     */
    private @Nullable List<String> credentialSpecs;
    /**
     * @return Dependencies on other containers in the task that control startup order.
     * 
     * ECS reverses the dependency order during shutdown.
     * 
     * For more information, see [container
     * dependencies](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDependency.html).
     * 
     */
    private @Nullable List<ContainerDefinitionDependency> dependsOn;
    /**
     * @return Whether to disable networking in the container. Not supported for Windows containers.
     * 
     * For more information, see
     * [disableNetworking](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-disableNetworking).
     * 
     */
    private @Nullable Boolean disableNetworking;
    /**
     * @return DNS search domains for the container. Not supported for Windows containers.
     * 
     * For more information, see
     * [dnsSearchDomains](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-dnsSearchDomains).
     * 
     */
    private @Nullable List<String> dnsSearchDomains;
    /**
     * @return DNS servers for the container. Not supported for Windows containers.
     * 
     * For more information, see
     * [dnsServers](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-dnsServers).
     * 
     */
    private @Nullable List<String> dnsServers;
    /**
     * @return Labels to add to the container.
     * 
     * For more information, see
     * [dockerLabels](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-dockerLabels).
     * 
     */
    private @Nullable Map<String,String> dockerLabels;
    /**
     * @return Security options for the container, such as SELinux labels or an AppArmor profile.
     * 
     * Not supported for Fargate tasks. The container instance must support the selected security
     * system. Use `credentialSpecs` for Active Directory authentication.
     * 
     * For more information, see
     * [dockerSecurityOptions](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-dockerSecurityOptions).
     * 
     */
    private @Nullable List<String> dockerSecurityOptions;
    /**
     * @return The entry point passed to the container.
     * 
     * For more information, see
     * [entryPoint](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-entryPoint).
     * 
     */
    private @Nullable List<String> entryPoint;
    /**
     * @return Environment variables passed to the container. Use `secrets` for sensitive values.
     * 
     * For more information, see [environment
     * variables](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html).
     * 
     */
    private @Nullable List<KeyValuePair> environment;
    /**
     * @return S3 environment files passed to the container. Specify at most ten `.env` files.
     * 
     * Values in `environment` take precedence over file values. Files are processed in list order;
     * the first value for a variable takes precedence over values in later files. Not supported for
     * Windows containers.
     * 
     * For more information, see [environment
     * files](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/use-environment-file.html).
     * 
     */
    private @Nullable List<ContainerDefinitionEnvironmentFile> environmentFiles;
    /**
     * @return Whether the container is essential to the task.
     * 
     * If an essential container stops, ECS stops all other containers in the task. Each task must
     * have at least one essential container.
     * 
     * Default - `true` in ECS.
     * 
     * For more information, see
     * [essential](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-essential).
     * 
     */
    private @Nullable Boolean essential;
    /**
     * @return Hostname and IP address mappings to add to the container&#39;s `/etc/hosts` file.
     * 
     * Not supported for Windows containers or the `awsvpc` network mode.
     * 
     * For more information, see
     * [extraHosts](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-extraHosts).
     * 
     */
    private @Nullable List<HostEntry> extraHosts;
    /**
     * @return FireLens log router settings for the container.
     * 
     * For more information, see [custom log
     * routing](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html).
     * 
     */
    private @Nullable FirelensConfiguration firelensConfiguration;
    /**
     * @return The health check command and settings for the container.
     * 
     * ECS only monitors health checks specified in the task definition, not checks configured only in
     * the container image.
     * 
     * For more information, see [container health
     * checks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/healthcheck.html).
     * 
     */
    private @Nullable ContainerDefinitionHealthCheck healthCheck;
    /**
     * @return The container hostname. Not supported with the `awsvpc` network mode.
     * 
     * For more information, see
     * [hostname](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-hostname).
     * 
     */
    private @Nullable String hostname;
    /**
     * @return The image used to start the container, specified by name, tag, or digest.
     * 
     * For private registries, include the registry address, such as `registry/repository:tag` or
     * `registry/repository{@literal @}sha256:digest`. Image updates do not update already running tasks.
     * 
     * For more information, see
     * [image](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-image).
     * 
     */
    private String image;
    /**
     * @return Whether to keep standard input open for the container.
     * 
     * For more information, see
     * [interactive](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-interactive).
     * 
     */
    private @Nullable Boolean interactive;
    /**
     * @return Links to other containers, specified as a container name or `name:alias`.
     * 
     * Supported only with the `bridge` network mode and not for Windows containers. Links do not
     * provide network isolation.
     * 
     * For more information, see
     * [links](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-links).
     * 
     */
    private @Nullable List<String> links;
    /**
     * @return Linux-specific container settings, such as kernel capabilities and devices.
     * 
     * Not supported for Windows containers.
     * 
     * For more information, see [Linux
     * parameters](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LinuxParameters.html).
     * 
     */
    private @Nullable LinuxParameters linuxParameters;
    /**
     * @return The log driver and its settings for the container.
     * 
     * On EC2, the driver must be available and configured on the container instance.
     * 
     * For more information, see [log
     * configuration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html).
     * 
     */
    private @Nullable LogConfiguration logConfiguration;
    /**
     * @return The hard memory limit, in MiB. The container is killed if it exceeds this limit.
     * 
     * Must be greater than `memoryReservation` when both are set. On EC2, specify memory at the task
     * or container level. Total container memory reservations must be below the task memory value, if
     * set. Container-level memory is optional on Fargate.
     * 
     * For more information, see
     * [memory](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-memory).
     * 
     */
    private @Nullable Double memory;
    /**
     * @return The soft memory limit, in MiB, reserved for the container during placement.
     * 
     * The container can use more memory, up to `memory` or the available instance memory. If both
     * limits are set, `memory` must be greater. Without task-level memory, set a nonzero `memory` or
     * `memoryReservation` value.
     * 
     * For more information, see
     * [memoryReservation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-memoryReservation).
     * 
     */
    private @Nullable Double memoryReservation;
    /**
     * @return Data volumes to mount in the container.
     * 
     * Windows mounts must use directories on the same drive as `$env:ProgramData`.
     * 
     * For more information, see
     * [mountPoints](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-mountPoints).
     * 
     */
    private @Nullable List<MountPoint> mountPoints;
    /**
     * @return The container name, used by other containers to reference it.
     * 
     * Use up to 255 letters, numbers, underscores, or hyphens.
     * 
     * For more information, see
     * [name](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-name).
     * 
     */
    private String name;
    /**
     * @return Ports to expose from the container.
     * 
     * With `awsvpc` or `host` networking, omit `hostPort` or match it to `containerPort`. Port
     * mappings are not supported with the `none` network mode.
     * 
     * For more information, see [port
     * mappings](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html).
     * 
     */
    private @Nullable List<PortMapping> portMappings;
    /**
     * @return Whether to give the container elevated privileges on the host.
     * 
     * Not supported for Windows containers or Fargate tasks.
     * 
     * For more information, see
     * [privileged](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-privileged).
     * 
     */
    private @Nullable Boolean privileged;
    /**
     * @return Whether to allocate a TTY for the container.
     * 
     * For more information, see
     * [pseudoTerminal](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-pseudoTerminal).
     * 
     */
    private @Nullable Boolean pseudoTerminal;
    /**
     * @return Whether the container has read-only access to its root file system.
     * 
     * Not supported for Windows containers.
     * 
     * For more information, see
     * [readonlyRootFilesystem](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-readonlyRootFilesystem).
     * 
     */
    private @Nullable Boolean readonlyRootFilesystem;
    /**
     * @return Credentials for authentication to a private image registry.
     * 
     * For more information, see [repository
     * credentials](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RepositoryCredentials.html).
     * 
     */
    private @Nullable RepositoryCredentials repositoryCredentials;
    /**
     * @return Specialized resources to assign to the container, such as GPUs or Neuron devices.
     * 
     * For more information, see [resource
     * requirements](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ResourceRequirement.html).
     * 
     */
    private @Nullable List<ResourceRequirement> resourceRequirements;
    /**
     * @return Settings that let ECS restart the container without replacing the task.
     * 
     * For more information, see [container restart
     * policies](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy.html).
     * 
     */
    private @Nullable ContainerRestartPolicy restartPolicy;
    /**
     * @return Secrets to pass to the container as environment variables.
     * 
     * For more information, see [sensitive
     * data](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html).
     * 
     */
    private @Nullable List<ContainerDefinitionSecret> secrets;
    /**
     * @return The time, in seconds, allowed for this container to satisfy another container&#39;s dependency.
     * 
     * If the required condition is not met in time, the dependent container does not start and the
     * task stops. Fargate accepts 2 through 120 seconds. The agent&#39;s `ECS_CONTAINER_START_TIMEOUT`
     * setting is enforced independently.
     * 
     * For more information, see
     * [startTimeout](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-startTimeout).
     * 
     */
    private @Nullable Double startTimeout;
    /**
     * @return The time, in seconds, to wait for the container to stop before it is forcibly killed.
     * 
     * Fargate accepts 2 through 120 seconds.
     * 
     * Default - 30 seconds on Fargate. On EC2, the agent&#39;s `ECS_CONTAINER_STOP_TIMEOUT` setting, or
     * 30 seconds if that setting is absent.
     * 
     * For more information, see
     * [stopTimeout](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-stopTimeout).
     * 
     */
    private @Nullable Double stopTimeout;
    /**
     * @return Namespaced kernel parameters to set in the container.
     * 
     * Settings can affect other containers that share the same namespace. Not supported for Windows
     * containers.
     * 
     * For more information, see [system
     * controls](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_SystemControl.html).
     * 
     */
    private @Nullable List<ContainerDefinitionSystemControl> systemControls;
    /**
     * @return Operating-system resource limits for the container. Not supported for Windows containers.
     * 
     * For more information, see
     * [ulimits](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Ulimit.html).
     * 
     */
    private @Nullable List<Ulimit> ulimits;
    /**
     * @return The user that runs commands inside the container, as a name, ID, or user and group pair.
     * 
     * Use a non-root user, especially with `host` networking. Not supported for Windows containers.
     * 
     * For more information, see
     * [user](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-user).
     * 
     */
    private @Nullable String user;
    /**
     * @return Whether ECS resolves the image tag to a digest. When disabled, ECS uses the original image URI.
     * 
     * Default - `enabled` in ECS.
     * 
     * For more information, see [container image
     * resolution](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-ecs.html#deployment-container-image-stability).
     * 
     */
    private @Nullable ContainerDefinitionVersionConsistency versionConsistency;
    /**
     * @return Data volumes to mount from another container in the same task.
     * 
     * For more information, see [volumes from other
     * containers](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_VolumeFrom.html).
     * 
     */
    private @Nullable List<ContainerDefinitionVolumeFrom> volumesFrom;
    /**
     * @return The working directory in which commands run inside the container.
     * 
     * For more information, see
     * [workingDirectory](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-workingDirectory).
     * 
     */
    private @Nullable String workingDirectory;

    private ContainerDefinitionArgs() {}
    /**
     * @return The command passed to the container. Use a separate array item for each argument.
     * 
     * For more information, see
     * [command](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-command).
     * 
     */
    public List<String> command() {
        return this.command == null ? List.of() : this.command;
    }
    /**
     * @return The CPU units reserved for the container. There are 1,024 CPU units per vCPU.
     * 
     * On Linux, this controls relative CPU shares, not a hard limit. On Windows, it is a hard limit.
     * For Fargate, the total container CPU reservation must be below the task CPU value.
     * 
     * For more information, see
     * [cpu](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-cpu).
     * 
     */
    public Optional<Double> cpu() {
        return Optional.ofNullable(this.cpu);
    }
    /**
     * @return Credential specifications for Active Directory authentication. Specify at most one entry.
     * 
     * Use `credentialspec:ARN` or `credentialspecdomainless:ARN`, with an SSM or S3 ARN. Prefer this
     * property to `dockerSecurityOptions` for credential specifications.
     * 
     * For more information, see
     * [credentialSpecs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-credentialSpecs).
     * 
     */
    public List<String> credentialSpecs() {
        return this.credentialSpecs == null ? List.of() : this.credentialSpecs;
    }
    /**
     * @return Dependencies on other containers in the task that control startup order.
     * 
     * ECS reverses the dependency order during shutdown.
     * 
     * For more information, see [container
     * dependencies](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDependency.html).
     * 
     */
    public List<ContainerDefinitionDependency> dependsOn() {
        return this.dependsOn == null ? List.of() : this.dependsOn;
    }
    /**
     * @return Whether to disable networking in the container. Not supported for Windows containers.
     * 
     * For more information, see
     * [disableNetworking](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-disableNetworking).
     * 
     */
    public Optional<Boolean> disableNetworking() {
        return Optional.ofNullable(this.disableNetworking);
    }
    /**
     * @return DNS search domains for the container. Not supported for Windows containers.
     * 
     * For more information, see
     * [dnsSearchDomains](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-dnsSearchDomains).
     * 
     */
    public List<String> dnsSearchDomains() {
        return this.dnsSearchDomains == null ? List.of() : this.dnsSearchDomains;
    }
    /**
     * @return DNS servers for the container. Not supported for Windows containers.
     * 
     * For more information, see
     * [dnsServers](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-dnsServers).
     * 
     */
    public List<String> dnsServers() {
        return this.dnsServers == null ? List.of() : this.dnsServers;
    }
    /**
     * @return Labels to add to the container.
     * 
     * For more information, see
     * [dockerLabels](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-dockerLabels).
     * 
     */
    public Map<String,String> dockerLabels() {
        return this.dockerLabels == null ? Map.of() : this.dockerLabels;
    }
    /**
     * @return Security options for the container, such as SELinux labels or an AppArmor profile.
     * 
     * Not supported for Fargate tasks. The container instance must support the selected security
     * system. Use `credentialSpecs` for Active Directory authentication.
     * 
     * For more information, see
     * [dockerSecurityOptions](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-dockerSecurityOptions).
     * 
     */
    public List<String> dockerSecurityOptions() {
        return this.dockerSecurityOptions == null ? List.of() : this.dockerSecurityOptions;
    }
    /**
     * @return The entry point passed to the container.
     * 
     * For more information, see
     * [entryPoint](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-entryPoint).
     * 
     */
    public List<String> entryPoint() {
        return this.entryPoint == null ? List.of() : this.entryPoint;
    }
    /**
     * @return Environment variables passed to the container. Use `secrets` for sensitive values.
     * 
     * For more information, see [environment
     * variables](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html).
     * 
     */
    public List<KeyValuePair> environment() {
        return this.environment == null ? List.of() : this.environment;
    }
    /**
     * @return S3 environment files passed to the container. Specify at most ten `.env` files.
     * 
     * Values in `environment` take precedence over file values. Files are processed in list order;
     * the first value for a variable takes precedence over values in later files. Not supported for
     * Windows containers.
     * 
     * For more information, see [environment
     * files](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/use-environment-file.html).
     * 
     */
    public List<ContainerDefinitionEnvironmentFile> environmentFiles() {
        return this.environmentFiles == null ? List.of() : this.environmentFiles;
    }
    /**
     * @return Whether the container is essential to the task.
     * 
     * If an essential container stops, ECS stops all other containers in the task. Each task must
     * have at least one essential container.
     * 
     * Default - `true` in ECS.
     * 
     * For more information, see
     * [essential](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-essential).
     * 
     */
    public Optional<Boolean> essential() {
        return Optional.ofNullable(this.essential);
    }
    /**
     * @return Hostname and IP address mappings to add to the container&#39;s `/etc/hosts` file.
     * 
     * Not supported for Windows containers or the `awsvpc` network mode.
     * 
     * For more information, see
     * [extraHosts](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-extraHosts).
     * 
     */
    public List<HostEntry> extraHosts() {
        return this.extraHosts == null ? List.of() : this.extraHosts;
    }
    /**
     * @return FireLens log router settings for the container.
     * 
     * For more information, see [custom log
     * routing](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html).
     * 
     */
    public Optional<FirelensConfiguration> firelensConfiguration() {
        return Optional.ofNullable(this.firelensConfiguration);
    }
    /**
     * @return The health check command and settings for the container.
     * 
     * ECS only monitors health checks specified in the task definition, not checks configured only in
     * the container image.
     * 
     * For more information, see [container health
     * checks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/healthcheck.html).
     * 
     */
    public Optional<ContainerDefinitionHealthCheck> healthCheck() {
        return Optional.ofNullable(this.healthCheck);
    }
    /**
     * @return The container hostname. Not supported with the `awsvpc` network mode.
     * 
     * For more information, see
     * [hostname](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-hostname).
     * 
     */
    public Optional<String> hostname() {
        return Optional.ofNullable(this.hostname);
    }
    /**
     * @return The image used to start the container, specified by name, tag, or digest.
     * 
     * For private registries, include the registry address, such as `registry/repository:tag` or
     * `registry/repository{@literal @}sha256:digest`. Image updates do not update already running tasks.
     * 
     * For more information, see
     * [image](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-image).
     * 
     */
    public String image() {
        return this.image;
    }
    /**
     * @return Whether to keep standard input open for the container.
     * 
     * For more information, see
     * [interactive](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-interactive).
     * 
     */
    public Optional<Boolean> interactive() {
        return Optional.ofNullable(this.interactive);
    }
    /**
     * @return Links to other containers, specified as a container name or `name:alias`.
     * 
     * Supported only with the `bridge` network mode and not for Windows containers. Links do not
     * provide network isolation.
     * 
     * For more information, see
     * [links](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-links).
     * 
     */
    public List<String> links() {
        return this.links == null ? List.of() : this.links;
    }
    /**
     * @return Linux-specific container settings, such as kernel capabilities and devices.
     * 
     * Not supported for Windows containers.
     * 
     * For more information, see [Linux
     * parameters](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LinuxParameters.html).
     * 
     */
    public Optional<LinuxParameters> linuxParameters() {
        return Optional.ofNullable(this.linuxParameters);
    }
    /**
     * @return The log driver and its settings for the container.
     * 
     * On EC2, the driver must be available and configured on the container instance.
     * 
     * For more information, see [log
     * configuration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LogConfiguration.html).
     * 
     */
    public Optional<LogConfiguration> logConfiguration() {
        return Optional.ofNullable(this.logConfiguration);
    }
    /**
     * @return The hard memory limit, in MiB. The container is killed if it exceeds this limit.
     * 
     * Must be greater than `memoryReservation` when both are set. On EC2, specify memory at the task
     * or container level. Total container memory reservations must be below the task memory value, if
     * set. Container-level memory is optional on Fargate.
     * 
     * For more information, see
     * [memory](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-memory).
     * 
     */
    public Optional<Double> memory() {
        return Optional.ofNullable(this.memory);
    }
    /**
     * @return The soft memory limit, in MiB, reserved for the container during placement.
     * 
     * The container can use more memory, up to `memory` or the available instance memory. If both
     * limits are set, `memory` must be greater. Without task-level memory, set a nonzero `memory` or
     * `memoryReservation` value.
     * 
     * For more information, see
     * [memoryReservation](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-memoryReservation).
     * 
     */
    public Optional<Double> memoryReservation() {
        return Optional.ofNullable(this.memoryReservation);
    }
    /**
     * @return Data volumes to mount in the container.
     * 
     * Windows mounts must use directories on the same drive as `$env:ProgramData`.
     * 
     * For more information, see
     * [mountPoints](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-mountPoints).
     * 
     */
    public List<MountPoint> mountPoints() {
        return this.mountPoints == null ? List.of() : this.mountPoints;
    }
    /**
     * @return The container name, used by other containers to reference it.
     * 
     * Use up to 255 letters, numbers, underscores, or hyphens.
     * 
     * For more information, see
     * [name](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-name).
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Ports to expose from the container.
     * 
     * With `awsvpc` or `host` networking, omit `hostPort` or match it to `containerPort`. Port
     * mappings are not supported with the `none` network mode.
     * 
     * For more information, see [port
     * mappings](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html).
     * 
     */
    public List<PortMapping> portMappings() {
        return this.portMappings == null ? List.of() : this.portMappings;
    }
    /**
     * @return Whether to give the container elevated privileges on the host.
     * 
     * Not supported for Windows containers or Fargate tasks.
     * 
     * For more information, see
     * [privileged](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-privileged).
     * 
     */
    public Optional<Boolean> privileged() {
        return Optional.ofNullable(this.privileged);
    }
    /**
     * @return Whether to allocate a TTY for the container.
     * 
     * For more information, see
     * [pseudoTerminal](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-pseudoTerminal).
     * 
     */
    public Optional<Boolean> pseudoTerminal() {
        return Optional.ofNullable(this.pseudoTerminal);
    }
    /**
     * @return Whether the container has read-only access to its root file system.
     * 
     * Not supported for Windows containers.
     * 
     * For more information, see
     * [readonlyRootFilesystem](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-readonlyRootFilesystem).
     * 
     */
    public Optional<Boolean> readonlyRootFilesystem() {
        return Optional.ofNullable(this.readonlyRootFilesystem);
    }
    /**
     * @return Credentials for authentication to a private image registry.
     * 
     * For more information, see [repository
     * credentials](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RepositoryCredentials.html).
     * 
     */
    public Optional<RepositoryCredentials> repositoryCredentials() {
        return Optional.ofNullable(this.repositoryCredentials);
    }
    /**
     * @return Specialized resources to assign to the container, such as GPUs or Neuron devices.
     * 
     * For more information, see [resource
     * requirements](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ResourceRequirement.html).
     * 
     */
    public List<ResourceRequirement> resourceRequirements() {
        return this.resourceRequirements == null ? List.of() : this.resourceRequirements;
    }
    /**
     * @return Settings that let ECS restart the container without replacing the task.
     * 
     * For more information, see [container restart
     * policies](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy.html).
     * 
     */
    public Optional<ContainerRestartPolicy> restartPolicy() {
        return Optional.ofNullable(this.restartPolicy);
    }
    /**
     * @return Secrets to pass to the container as environment variables.
     * 
     * For more information, see [sensitive
     * data](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html).
     * 
     */
    public List<ContainerDefinitionSecret> secrets() {
        return this.secrets == null ? List.of() : this.secrets;
    }
    /**
     * @return The time, in seconds, allowed for this container to satisfy another container&#39;s dependency.
     * 
     * If the required condition is not met in time, the dependent container does not start and the
     * task stops. Fargate accepts 2 through 120 seconds. The agent&#39;s `ECS_CONTAINER_START_TIMEOUT`
     * setting is enforced independently.
     * 
     * For more information, see
     * [startTimeout](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-startTimeout).
     * 
     */
    public Optional<Double> startTimeout() {
        return Optional.ofNullable(this.startTimeout);
    }
    /**
     * @return The time, in seconds, to wait for the container to stop before it is forcibly killed.
     * 
     * Fargate accepts 2 through 120 seconds.
     * 
     * Default - 30 seconds on Fargate. On EC2, the agent&#39;s `ECS_CONTAINER_STOP_TIMEOUT` setting, or
     * 30 seconds if that setting is absent.
     * 
     * For more information, see
     * [stopTimeout](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-stopTimeout).
     * 
     */
    public Optional<Double> stopTimeout() {
        return Optional.ofNullable(this.stopTimeout);
    }
    /**
     * @return Namespaced kernel parameters to set in the container.
     * 
     * Settings can affect other containers that share the same namespace. Not supported for Windows
     * containers.
     * 
     * For more information, see [system
     * controls](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_SystemControl.html).
     * 
     */
    public List<ContainerDefinitionSystemControl> systemControls() {
        return this.systemControls == null ? List.of() : this.systemControls;
    }
    /**
     * @return Operating-system resource limits for the container. Not supported for Windows containers.
     * 
     * For more information, see
     * [ulimits](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Ulimit.html).
     * 
     */
    public List<Ulimit> ulimits() {
        return this.ulimits == null ? List.of() : this.ulimits;
    }
    /**
     * @return The user that runs commands inside the container, as a name, ID, or user and group pair.
     * 
     * Use a non-root user, especially with `host` networking. Not supported for Windows containers.
     * 
     * For more information, see
     * [user](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-user).
     * 
     */
    public Optional<String> user() {
        return Optional.ofNullable(this.user);
    }
    /**
     * @return Whether ECS resolves the image tag to a digest. When disabled, ECS uses the original image URI.
     * 
     * Default - `enabled` in ECS.
     * 
     * For more information, see [container image
     * resolution](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-ecs.html#deployment-container-image-stability).
     * 
     */
    public Optional<ContainerDefinitionVersionConsistency> versionConsistency() {
        return Optional.ofNullable(this.versionConsistency);
    }
    /**
     * @return Data volumes to mount from another container in the same task.
     * 
     * For more information, see [volumes from other
     * containers](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_VolumeFrom.html).
     * 
     */
    public List<ContainerDefinitionVolumeFrom> volumesFrom() {
        return this.volumesFrom == null ? List.of() : this.volumesFrom;
    }
    /**
     * @return The working directory in which commands run inside the container.
     * 
     * For more information, see
     * [workingDirectory](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-workingDirectory).
     * 
     */
    public Optional<String> workingDirectory() {
        return Optional.ofNullable(this.workingDirectory);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ContainerDefinitionArgs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> command;
        private @Nullable Double cpu;
        private @Nullable List<String> credentialSpecs;
        private @Nullable List<ContainerDefinitionDependency> dependsOn;
        private @Nullable Boolean disableNetworking;
        private @Nullable List<String> dnsSearchDomains;
        private @Nullable List<String> dnsServers;
        private @Nullable Map<String,String> dockerLabels;
        private @Nullable List<String> dockerSecurityOptions;
        private @Nullable List<String> entryPoint;
        private @Nullable List<KeyValuePair> environment;
        private @Nullable List<ContainerDefinitionEnvironmentFile> environmentFiles;
        private @Nullable Boolean essential;
        private @Nullable List<HostEntry> extraHosts;
        private @Nullable FirelensConfiguration firelensConfiguration;
        private @Nullable ContainerDefinitionHealthCheck healthCheck;
        private @Nullable String hostname;
        private String image;
        private @Nullable Boolean interactive;
        private @Nullable List<String> links;
        private @Nullable LinuxParameters linuxParameters;
        private @Nullable LogConfiguration logConfiguration;
        private @Nullable Double memory;
        private @Nullable Double memoryReservation;
        private @Nullable List<MountPoint> mountPoints;
        private String name;
        private @Nullable List<PortMapping> portMappings;
        private @Nullable Boolean privileged;
        private @Nullable Boolean pseudoTerminal;
        private @Nullable Boolean readonlyRootFilesystem;
        private @Nullable RepositoryCredentials repositoryCredentials;
        private @Nullable List<ResourceRequirement> resourceRequirements;
        private @Nullable ContainerRestartPolicy restartPolicy;
        private @Nullable List<ContainerDefinitionSecret> secrets;
        private @Nullable Double startTimeout;
        private @Nullable Double stopTimeout;
        private @Nullable List<ContainerDefinitionSystemControl> systemControls;
        private @Nullable List<Ulimit> ulimits;
        private @Nullable String user;
        private @Nullable ContainerDefinitionVersionConsistency versionConsistency;
        private @Nullable List<ContainerDefinitionVolumeFrom> volumesFrom;
        private @Nullable String workingDirectory;
        public Builder() {}
        public Builder(ContainerDefinitionArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.command = defaults.command;
    	      this.cpu = defaults.cpu;
    	      this.credentialSpecs = defaults.credentialSpecs;
    	      this.dependsOn = defaults.dependsOn;
    	      this.disableNetworking = defaults.disableNetworking;
    	      this.dnsSearchDomains = defaults.dnsSearchDomains;
    	      this.dnsServers = defaults.dnsServers;
    	      this.dockerLabels = defaults.dockerLabels;
    	      this.dockerSecurityOptions = defaults.dockerSecurityOptions;
    	      this.entryPoint = defaults.entryPoint;
    	      this.environment = defaults.environment;
    	      this.environmentFiles = defaults.environmentFiles;
    	      this.essential = defaults.essential;
    	      this.extraHosts = defaults.extraHosts;
    	      this.firelensConfiguration = defaults.firelensConfiguration;
    	      this.healthCheck = defaults.healthCheck;
    	      this.hostname = defaults.hostname;
    	      this.image = defaults.image;
    	      this.interactive = defaults.interactive;
    	      this.links = defaults.links;
    	      this.linuxParameters = defaults.linuxParameters;
    	      this.logConfiguration = defaults.logConfiguration;
    	      this.memory = defaults.memory;
    	      this.memoryReservation = defaults.memoryReservation;
    	      this.mountPoints = defaults.mountPoints;
    	      this.name = defaults.name;
    	      this.portMappings = defaults.portMappings;
    	      this.privileged = defaults.privileged;
    	      this.pseudoTerminal = defaults.pseudoTerminal;
    	      this.readonlyRootFilesystem = defaults.readonlyRootFilesystem;
    	      this.repositoryCredentials = defaults.repositoryCredentials;
    	      this.resourceRequirements = defaults.resourceRequirements;
    	      this.restartPolicy = defaults.restartPolicy;
    	      this.secrets = defaults.secrets;
    	      this.startTimeout = defaults.startTimeout;
    	      this.stopTimeout = defaults.stopTimeout;
    	      this.systemControls = defaults.systemControls;
    	      this.ulimits = defaults.ulimits;
    	      this.user = defaults.user;
    	      this.versionConsistency = defaults.versionConsistency;
    	      this.volumesFrom = defaults.volumesFrom;
    	      this.workingDirectory = defaults.workingDirectory;
        }

        @CustomType.Setter
        public Builder command(@Nullable List<String> command) {

            this.command = command;
            return this;
        }
        public Builder command(String... command) {
            return command(List.of(command));
        }
        @CustomType.Setter
        public Builder cpu(@Nullable Double cpu) {

            this.cpu = cpu;
            return this;
        }
        @CustomType.Setter
        public Builder credentialSpecs(@Nullable List<String> credentialSpecs) {

            this.credentialSpecs = credentialSpecs;
            return this;
        }
        public Builder credentialSpecs(String... credentialSpecs) {
            return credentialSpecs(List.of(credentialSpecs));
        }
        @CustomType.Setter
        public Builder dependsOn(@Nullable List<ContainerDefinitionDependency> dependsOn) {

            this.dependsOn = dependsOn;
            return this;
        }
        public Builder dependsOn(ContainerDefinitionDependency... dependsOn) {
            return dependsOn(List.of(dependsOn));
        }
        @CustomType.Setter
        public Builder disableNetworking(@Nullable Boolean disableNetworking) {

            this.disableNetworking = disableNetworking;
            return this;
        }
        @CustomType.Setter
        public Builder dnsSearchDomains(@Nullable List<String> dnsSearchDomains) {

            this.dnsSearchDomains = dnsSearchDomains;
            return this;
        }
        public Builder dnsSearchDomains(String... dnsSearchDomains) {
            return dnsSearchDomains(List.of(dnsSearchDomains));
        }
        @CustomType.Setter
        public Builder dnsServers(@Nullable List<String> dnsServers) {

            this.dnsServers = dnsServers;
            return this;
        }
        public Builder dnsServers(String... dnsServers) {
            return dnsServers(List.of(dnsServers));
        }
        @CustomType.Setter
        public Builder dockerLabels(@Nullable Map<String,String> dockerLabels) {

            this.dockerLabels = dockerLabels;
            return this;
        }
        @CustomType.Setter
        public Builder dockerSecurityOptions(@Nullable List<String> dockerSecurityOptions) {

            this.dockerSecurityOptions = dockerSecurityOptions;
            return this;
        }
        public Builder dockerSecurityOptions(String... dockerSecurityOptions) {
            return dockerSecurityOptions(List.of(dockerSecurityOptions));
        }
        @CustomType.Setter
        public Builder entryPoint(@Nullable List<String> entryPoint) {

            this.entryPoint = entryPoint;
            return this;
        }
        public Builder entryPoint(String... entryPoint) {
            return entryPoint(List.of(entryPoint));
        }
        @CustomType.Setter
        public Builder environment(@Nullable List<KeyValuePair> environment) {

            this.environment = environment;
            return this;
        }
        public Builder environment(KeyValuePair... environment) {
            return environment(List.of(environment));
        }
        @CustomType.Setter
        public Builder environmentFiles(@Nullable List<ContainerDefinitionEnvironmentFile> environmentFiles) {

            this.environmentFiles = environmentFiles;
            return this;
        }
        public Builder environmentFiles(ContainerDefinitionEnvironmentFile... environmentFiles) {
            return environmentFiles(List.of(environmentFiles));
        }
        @CustomType.Setter
        public Builder essential(@Nullable Boolean essential) {

            this.essential = essential;
            return this;
        }
        @CustomType.Setter
        public Builder extraHosts(@Nullable List<HostEntry> extraHosts) {

            this.extraHosts = extraHosts;
            return this;
        }
        public Builder extraHosts(HostEntry... extraHosts) {
            return extraHosts(List.of(extraHosts));
        }
        @CustomType.Setter
        public Builder firelensConfiguration(@Nullable FirelensConfiguration firelensConfiguration) {

            this.firelensConfiguration = firelensConfiguration;
            return this;
        }
        @CustomType.Setter
        public Builder healthCheck(@Nullable ContainerDefinitionHealthCheck healthCheck) {

            this.healthCheck = healthCheck;
            return this;
        }
        @CustomType.Setter
        public Builder hostname(@Nullable String hostname) {

            this.hostname = hostname;
            return this;
        }
        @CustomType.Setter
        public Builder image(String image) {
            if (image == null) {
              throw new MissingRequiredPropertyException("ContainerDefinitionArgs", "image");
            }
            this.image = image;
            return this;
        }
        @CustomType.Setter
        public Builder interactive(@Nullable Boolean interactive) {

            this.interactive = interactive;
            return this;
        }
        @CustomType.Setter
        public Builder links(@Nullable List<String> links) {

            this.links = links;
            return this;
        }
        public Builder links(String... links) {
            return links(List.of(links));
        }
        @CustomType.Setter
        public Builder linuxParameters(@Nullable LinuxParameters linuxParameters) {

            this.linuxParameters = linuxParameters;
            return this;
        }
        @CustomType.Setter
        public Builder logConfiguration(@Nullable LogConfiguration logConfiguration) {

            this.logConfiguration = logConfiguration;
            return this;
        }
        @CustomType.Setter
        public Builder memory(@Nullable Double memory) {

            this.memory = memory;
            return this;
        }
        @CustomType.Setter
        public Builder memoryReservation(@Nullable Double memoryReservation) {

            this.memoryReservation = memoryReservation;
            return this;
        }
        @CustomType.Setter
        public Builder mountPoints(@Nullable List<MountPoint> mountPoints) {

            this.mountPoints = mountPoints;
            return this;
        }
        public Builder mountPoints(MountPoint... mountPoints) {
            return mountPoints(List.of(mountPoints));
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("ContainerDefinitionArgs", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder portMappings(@Nullable List<PortMapping> portMappings) {

            this.portMappings = portMappings;
            return this;
        }
        public Builder portMappings(PortMapping... portMappings) {
            return portMappings(List.of(portMappings));
        }
        @CustomType.Setter
        public Builder privileged(@Nullable Boolean privileged) {

            this.privileged = privileged;
            return this;
        }
        @CustomType.Setter
        public Builder pseudoTerminal(@Nullable Boolean pseudoTerminal) {

            this.pseudoTerminal = pseudoTerminal;
            return this;
        }
        @CustomType.Setter
        public Builder readonlyRootFilesystem(@Nullable Boolean readonlyRootFilesystem) {

            this.readonlyRootFilesystem = readonlyRootFilesystem;
            return this;
        }
        @CustomType.Setter
        public Builder repositoryCredentials(@Nullable RepositoryCredentials repositoryCredentials) {

            this.repositoryCredentials = repositoryCredentials;
            return this;
        }
        @CustomType.Setter
        public Builder resourceRequirements(@Nullable List<ResourceRequirement> resourceRequirements) {

            this.resourceRequirements = resourceRequirements;
            return this;
        }
        public Builder resourceRequirements(ResourceRequirement... resourceRequirements) {
            return resourceRequirements(List.of(resourceRequirements));
        }
        @CustomType.Setter
        public Builder restartPolicy(@Nullable ContainerRestartPolicy restartPolicy) {

            this.restartPolicy = restartPolicy;
            return this;
        }
        @CustomType.Setter
        public Builder secrets(@Nullable List<ContainerDefinitionSecret> secrets) {

            this.secrets = secrets;
            return this;
        }
        public Builder secrets(ContainerDefinitionSecret... secrets) {
            return secrets(List.of(secrets));
        }
        @CustomType.Setter
        public Builder startTimeout(@Nullable Double startTimeout) {

            this.startTimeout = startTimeout;
            return this;
        }
        @CustomType.Setter
        public Builder stopTimeout(@Nullable Double stopTimeout) {

            this.stopTimeout = stopTimeout;
            return this;
        }
        @CustomType.Setter
        public Builder systemControls(@Nullable List<ContainerDefinitionSystemControl> systemControls) {

            this.systemControls = systemControls;
            return this;
        }
        public Builder systemControls(ContainerDefinitionSystemControl... systemControls) {
            return systemControls(List.of(systemControls));
        }
        @CustomType.Setter
        public Builder ulimits(@Nullable List<Ulimit> ulimits) {

            this.ulimits = ulimits;
            return this;
        }
        public Builder ulimits(Ulimit... ulimits) {
            return ulimits(List.of(ulimits));
        }
        @CustomType.Setter
        public Builder user(@Nullable String user) {

            this.user = user;
            return this;
        }
        @CustomType.Setter
        public Builder versionConsistency(@Nullable ContainerDefinitionVersionConsistency versionConsistency) {

            this.versionConsistency = versionConsistency;
            return this;
        }
        @CustomType.Setter
        public Builder volumesFrom(@Nullable List<ContainerDefinitionVolumeFrom> volumesFrom) {

            this.volumesFrom = volumesFrom;
            return this;
        }
        public Builder volumesFrom(ContainerDefinitionVolumeFrom... volumesFrom) {
            return volumesFrom(List.of(volumesFrom));
        }
        @CustomType.Setter
        public Builder workingDirectory(@Nullable String workingDirectory) {

            this.workingDirectory = workingDirectory;
            return this;
        }
        public ContainerDefinitionArgs build() {
            final var _resultValue = new ContainerDefinitionArgs();
            _resultValue.command = command;
            _resultValue.cpu = cpu;
            _resultValue.credentialSpecs = credentialSpecs;
            _resultValue.dependsOn = dependsOn;
            _resultValue.disableNetworking = disableNetworking;
            _resultValue.dnsSearchDomains = dnsSearchDomains;
            _resultValue.dnsServers = dnsServers;
            _resultValue.dockerLabels = dockerLabels;
            _resultValue.dockerSecurityOptions = dockerSecurityOptions;
            _resultValue.entryPoint = entryPoint;
            _resultValue.environment = environment;
            _resultValue.environmentFiles = environmentFiles;
            _resultValue.essential = essential;
            _resultValue.extraHosts = extraHosts;
            _resultValue.firelensConfiguration = firelensConfiguration;
            _resultValue.healthCheck = healthCheck;
            _resultValue.hostname = hostname;
            _resultValue.image = image;
            _resultValue.interactive = interactive;
            _resultValue.links = links;
            _resultValue.linuxParameters = linuxParameters;
            _resultValue.logConfiguration = logConfiguration;
            _resultValue.memory = memory;
            _resultValue.memoryReservation = memoryReservation;
            _resultValue.mountPoints = mountPoints;
            _resultValue.name = name;
            _resultValue.portMappings = portMappings;
            _resultValue.privileged = privileged;
            _resultValue.pseudoTerminal = pseudoTerminal;
            _resultValue.readonlyRootFilesystem = readonlyRootFilesystem;
            _resultValue.repositoryCredentials = repositoryCredentials;
            _resultValue.resourceRequirements = resourceRequirements;
            _resultValue.restartPolicy = restartPolicy;
            _resultValue.secrets = secrets;
            _resultValue.startTimeout = startTimeout;
            _resultValue.stopTimeout = stopTimeout;
            _resultValue.systemControls = systemControls;
            _resultValue.ulimits = ulimits;
            _resultValue.user = user;
            _resultValue.versionConsistency = versionConsistency;
            _resultValue.volumesFrom = volumesFrom;
            _resultValue.workingDirectory = workingDirectory;
            return _resultValue;
        }
    }
}
