// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsx.experimental_ecs.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class KernelCapabilities {
    /**
     * @return Linux capabilities to add. Fargate supports adding only `SYS_PTRACE`.
     * 
     * For supported names, see
     * [add](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_KernelCapabilities.html#ECS-Type-KernelCapabilities-add).
     * 
     */
    private @Nullable List<String> add;
    /**
     * @return Linux capabilities to remove. Use `ALL` to remove all default capabilities.
     * 
     * For supported names, see
     * [drop](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_KernelCapabilities.html#ECS-Type-KernelCapabilities-drop).
     * 
     */
    private @Nullable List<String> drop;

    private KernelCapabilities() {}
    /**
     * @return Linux capabilities to add. Fargate supports adding only `SYS_PTRACE`.
     * 
     * For supported names, see
     * [add](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_KernelCapabilities.html#ECS-Type-KernelCapabilities-add).
     * 
     */
    public List<String> add() {
        return this.add == null ? List.of() : this.add;
    }
    /**
     * @return Linux capabilities to remove. Use `ALL` to remove all default capabilities.
     * 
     * For supported names, see
     * [drop](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_KernelCapabilities.html#ECS-Type-KernelCapabilities-drop).
     * 
     */
    public List<String> drop() {
        return this.drop == null ? List.of() : this.drop;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(KernelCapabilities defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> add;
        private @Nullable List<String> drop;
        public Builder() {}
        public Builder(KernelCapabilities defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.add = defaults.add;
    	      this.drop = defaults.drop;
        }

        @CustomType.Setter
        public Builder add(@Nullable List<String> add) {

            this.add = add;
            return this;
        }
        public Builder add(String... add) {
            return add(List.of(add));
        }
        @CustomType.Setter
        public Builder drop(@Nullable List<String> drop) {

            this.drop = drop;
            return this;
        }
        public Builder drop(String... drop) {
            return drop(List.of(drop));
        }
        public KernelCapabilities build() {
            final var _resultValue = new KernelCapabilities();
            _resultValue.add = add;
            _resultValue.drop = drop;
            return _resultValue;
        }
    }
}
