// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export members:
export * from "./dashboard";
export * from "./metric";
export * from "./metrics";
export * from "./widget";
export * from "./widgets_annotations";
export * from "./widgets_flow";
export * from "./widgets_graph";
export * from "./widgets_json";
export * from "./widgets_simple";
