// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsx.ecs.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TaskDefinitionSystemControlArgs extends com.pulumi.resources.ResourceArgs {

    public static final TaskDefinitionSystemControlArgs Empty = new TaskDefinitionSystemControlArgs();

    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    @Import(name="value")
    private @Nullable Output<String> value;

    public Optional<Output<String>> value() {
        return Optional.ofNullable(this.value);
    }

    private TaskDefinitionSystemControlArgs() {}

    private TaskDefinitionSystemControlArgs(TaskDefinitionSystemControlArgs $) {
        this.namespace = $.namespace;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TaskDefinitionSystemControlArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TaskDefinitionSystemControlArgs $;

        public Builder() {
            $ = new TaskDefinitionSystemControlArgs();
        }

        public Builder(TaskDefinitionSystemControlArgs defaults) {
            $ = new TaskDefinitionSystemControlArgs(Objects.requireNonNull(defaults));
        }

        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        public Builder value(@Nullable Output<String> value) {
            $.value = value;
            return this;
        }

        public Builder value(String value) {
            return value(Output.of(value));
        }

        public TaskDefinitionSystemControlArgs build() {
            return $;
        }
    }

}
