// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsx.ec2.inputs;

import com.pulumi.aws.ec2.inputs.VpcEndpointDnsOptionsArgs;
import com.pulumi.aws.ec2.inputs.VpcEndpointSubnetConfigurationArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Provides a VPC Endpoint resource.
 * 
 * &gt; **NOTE on VPC Endpoints and VPC Endpoint Associations:** The provider provides both standalone VPC Endpoint Associations for
 * Route Tables - (an association between a VPC endpoint and a single &lt;span pulumi-lang-nodejs=&#34;`routeTableId`&#34; pulumi-lang-dotnet=&#34;`RouteTableId`&#34; pulumi-lang-go=&#34;`routeTableId`&#34; pulumi-lang-python=&#34;`route_table_id`&#34; pulumi-lang-yaml=&#34;`routeTableId`&#34; pulumi-lang-java=&#34;`routeTableId`&#34;&gt;`route_table_id`&lt;/span&gt;),
 * Security Groups - (an association between a VPC endpoint and a single &lt;span pulumi-lang-nodejs=&#34;`securityGroupId`&#34; pulumi-lang-dotnet=&#34;`SecurityGroupId`&#34; pulumi-lang-go=&#34;`securityGroupId`&#34; pulumi-lang-python=&#34;`security_group_id`&#34; pulumi-lang-yaml=&#34;`securityGroupId`&#34; pulumi-lang-java=&#34;`securityGroupId`&#34;&gt;`security_group_id`&lt;/span&gt;),
 * and Subnets - (an association between a VPC endpoint and a single &lt;span pulumi-lang-nodejs=&#34;`subnetId`&#34; pulumi-lang-dotnet=&#34;`SubnetId`&#34; pulumi-lang-go=&#34;`subnetId`&#34; pulumi-lang-python=&#34;`subnet_id`&#34; pulumi-lang-yaml=&#34;`subnetId`&#34; pulumi-lang-java=&#34;`subnetId`&#34;&gt;`subnet_id`&lt;/span&gt;) and
 * a VPC Endpoint resource with &lt;span pulumi-lang-nodejs=&#34;`routeTableIds`&#34; pulumi-lang-dotnet=&#34;`RouteTableIds`&#34; pulumi-lang-go=&#34;`routeTableIds`&#34; pulumi-lang-python=&#34;`route_table_ids`&#34; pulumi-lang-yaml=&#34;`routeTableIds`&#34; pulumi-lang-java=&#34;`routeTableIds`&#34;&gt;`route_table_ids`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`subnetIds`&#34; pulumi-lang-dotnet=&#34;`SubnetIds`&#34; pulumi-lang-go=&#34;`subnetIds`&#34; pulumi-lang-python=&#34;`subnet_ids`&#34; pulumi-lang-yaml=&#34;`subnetIds`&#34; pulumi-lang-java=&#34;`subnetIds`&#34;&gt;`subnet_ids`&lt;/span&gt; attributes.
 * Do not use the same resource ID in both a VPC Endpoint resource and a VPC Endpoint Association resource.
 * Doing so will cause a conflict of associations and will overwrite the association.
 * 
 * ## Example Usage
 * 
 * ### Basic
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aws.ec2.VpcEndpoint;
 * import com.pulumi.aws.ec2.VpcEndpointArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var s3 = new VpcEndpoint("s3", VpcEndpointArgs.builder()
 *             .vpcId(main.id())
 *             .serviceName("com.amazonaws.us-west-2.s3")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ### Basic w/ Tags
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aws.ec2.VpcEndpoint;
 * import com.pulumi.aws.ec2.VpcEndpointArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var s3 = new VpcEndpoint("s3", VpcEndpointArgs.builder()
 *             .vpcId(main.id())
 *             .serviceName("com.amazonaws.us-west-2.s3")
 *             .tags(Map.of("Environment", "test"))
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ### Interface Endpoint Type
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aws.ec2.VpcEndpoint;
 * import com.pulumi.aws.ec2.VpcEndpointArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var ec2 = new VpcEndpoint("ec2", VpcEndpointArgs.builder()
 *             .vpcId(main.id())
 *             .serviceName("com.amazonaws.us-west-2.ec2")
 *             .vpcEndpointType("Interface")
 *             .securityGroupIds(sg1.id())
 *             .privateDnsEnabled(true)
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ### Interface Endpoint Type with User-Defined IP Address
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aws.ec2.VpcEndpoint;
 * import com.pulumi.aws.ec2.VpcEndpointArgs;
 * import com.pulumi.aws.ec2.inputs.VpcEndpointSubnetConfigurationArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var ec2 = new VpcEndpoint("ec2", VpcEndpointArgs.builder()
 *             .vpcId(example.id())
 *             .serviceName("com.amazonaws.us-west-2.ec2")
 *             .vpcEndpointType("Interface")
 *             .subnetConfigurations(            
 *                 VpcEndpointSubnetConfigurationArgs.builder()
 *                     .ipv4("10.0.1.10")
 *                     .subnetId(example1.id())
 *                     .build(),
 *                 VpcEndpointSubnetConfigurationArgs.builder()
 *                     .ipv4("10.0.2.10")
 *                     .subnetId(example2.id())
 *                     .build())
 *             .subnetIds(            
 *                 example1.id(),
 *                 example2.id())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ### Gateway Load Balancer Endpoint Type
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aws.AwsFunctions;
 * import com.pulumi.aws.inputs.GetCallerIdentityArgs;
 * import com.pulumi.aws.ec2.VpcEndpointService;
 * import com.pulumi.aws.ec2.VpcEndpointServiceArgs;
 * import com.pulumi.aws.ec2.VpcEndpoint;
 * import com.pulumi.aws.ec2.VpcEndpointArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         final var current = AwsFunctions.getCallerIdentity(GetCallerIdentityArgs.builder()
 *             .build());
 * 
 *         var example = new VpcEndpointService("example", VpcEndpointServiceArgs.builder()
 *             .acceptanceRequired(false)
 *             .allowedPrincipals(current.arn())
 *             .gatewayLoadBalancerArns(exampleAwsLb.arn())
 *             .build());
 * 
 *         var exampleVpcEndpoint = new VpcEndpoint("exampleVpcEndpoint", VpcEndpointArgs.builder()
 *             .serviceName(example.serviceName())
 *             .subnetIds(exampleAwsSubnet.id())
 *             .vpcEndpointType(example.serviceType())
 *             .vpcId(exampleAwsVpc.id())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ### VPC Lattice Resource Configuration Endpoint Type
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aws.ec2.VpcEndpoint;
 * import com.pulumi.aws.ec2.VpcEndpointArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new VpcEndpoint("example", VpcEndpointArgs.builder()
 *             .resourceConfigurationArn(exampleAwsVpclatticeResourceConfiguration.arn())
 *             .subnetIds(exampleAwsSubnet.id())
 *             .vpcEndpointType("Resource")
 *             .vpcId(exampleAwsVpc.id())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ### VPC Lattice Service Network Endpoint Type
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.aws.ec2.VpcEndpoint;
 * import com.pulumi.aws.ec2.VpcEndpointArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new VpcEndpoint("example", VpcEndpointArgs.builder()
 *             .serviceNetworkArn(exampleAwsVpclatticeServiceNetwork.arn())
 *             .subnetIds(exampleAwsSubnet.id())
 *             .vpcEndpointType("ServiceNetwork")
 *             .vpcId(exampleAwsVpc.id())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
public final class VpcEndpointSpecArgs extends com.pulumi.resources.ResourceArgs {

    public static final VpcEndpointSpecArgs Empty = new VpcEndpointSpecArgs();

    /**
     * Accept the VPC endpoint (the VPC endpoint and service need to be in the same AWS account).
     * 
     */
    @Import(name="autoAccept")
    private @Nullable Boolean autoAccept;

    /**
     * @return Accept the VPC endpoint (the VPC endpoint and service need to be in the same AWS account).
     * 
     */
    public Optional<Boolean> autoAccept() {
        return Optional.ofNullable(this.autoAccept);
    }

    /**
     * The DNS options for the endpoint. See&lt;span pulumi-lang-nodejs=&#34; dnsOptions &#34; pulumi-lang-dotnet=&#34; DnsOptions &#34; pulumi-lang-go=&#34; dnsOptions &#34; pulumi-lang-python=&#34; dns_options &#34; pulumi-lang-yaml=&#34; dnsOptions &#34; pulumi-lang-java=&#34; dnsOptions &#34;&gt; dns_options &lt;/span&gt;below.
     * 
     */
    @Import(name="dnsOptions")
    private @Nullable Output<VpcEndpointDnsOptionsArgs> dnsOptions;

    /**
     * @return The DNS options for the endpoint. See&lt;span pulumi-lang-nodejs=&#34; dnsOptions &#34; pulumi-lang-dotnet=&#34; DnsOptions &#34; pulumi-lang-go=&#34; dnsOptions &#34; pulumi-lang-python=&#34; dns_options &#34; pulumi-lang-yaml=&#34; dnsOptions &#34; pulumi-lang-java=&#34; dnsOptions &#34;&gt; dns_options &lt;/span&gt;below.
     * 
     */
    public Optional<Output<VpcEndpointDnsOptionsArgs>> dnsOptions() {
        return Optional.ofNullable(this.dnsOptions);
    }

    /**
     * The IP address type for the endpoint. Valid values are &lt;span pulumi-lang-nodejs=&#34;`ipv4`&#34; pulumi-lang-dotnet=&#34;`Ipv4`&#34; pulumi-lang-go=&#34;`ipv4`&#34; pulumi-lang-python=&#34;`ipv4`&#34; pulumi-lang-yaml=&#34;`ipv4`&#34; pulumi-lang-java=&#34;`ipv4`&#34;&gt;`ipv4`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`dualstack`&#34; pulumi-lang-dotnet=&#34;`Dualstack`&#34; pulumi-lang-go=&#34;`dualstack`&#34; pulumi-lang-python=&#34;`dualstack`&#34; pulumi-lang-yaml=&#34;`dualstack`&#34; pulumi-lang-java=&#34;`dualstack`&#34;&gt;`dualstack`&lt;/span&gt;, and &lt;span pulumi-lang-nodejs=&#34;`ipv6`&#34; pulumi-lang-dotnet=&#34;`Ipv6`&#34; pulumi-lang-go=&#34;`ipv6`&#34; pulumi-lang-python=&#34;`ipv6`&#34; pulumi-lang-yaml=&#34;`ipv6`&#34; pulumi-lang-java=&#34;`ipv6`&#34;&gt;`ipv6`&lt;/span&gt;.
     * 
     */
    @Import(name="ipAddressType")
    private @Nullable Output<String> ipAddressType;

    /**
     * @return The IP address type for the endpoint. Valid values are &lt;span pulumi-lang-nodejs=&#34;`ipv4`&#34; pulumi-lang-dotnet=&#34;`Ipv4`&#34; pulumi-lang-go=&#34;`ipv4`&#34; pulumi-lang-python=&#34;`ipv4`&#34; pulumi-lang-yaml=&#34;`ipv4`&#34; pulumi-lang-java=&#34;`ipv4`&#34;&gt;`ipv4`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`dualstack`&#34; pulumi-lang-dotnet=&#34;`Dualstack`&#34; pulumi-lang-go=&#34;`dualstack`&#34; pulumi-lang-python=&#34;`dualstack`&#34; pulumi-lang-yaml=&#34;`dualstack`&#34; pulumi-lang-java=&#34;`dualstack`&#34;&gt;`dualstack`&lt;/span&gt;, and &lt;span pulumi-lang-nodejs=&#34;`ipv6`&#34; pulumi-lang-dotnet=&#34;`Ipv6`&#34; pulumi-lang-go=&#34;`ipv6`&#34; pulumi-lang-python=&#34;`ipv6`&#34; pulumi-lang-yaml=&#34;`ipv6`&#34; pulumi-lang-java=&#34;`ipv6`&#34;&gt;`ipv6`&lt;/span&gt;.
     * 
     */
    public Optional<Output<String>> ipAddressType() {
        return Optional.ofNullable(this.ipAddressType);
    }

    /**
     * A policy to attach to the endpoint that controls access to the service. This is a JSON formatted string. Defaults to full access. All `Gateway` and some `Interface` endpoints support policies - see the [relevant AWS documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-access.html) for more details.
     * 
     */
    @Import(name="policy")
    private @Nullable Output<String> policy;

    /**
     * @return A policy to attach to the endpoint that controls access to the service. This is a JSON formatted string. Defaults to full access. All `Gateway` and some `Interface` endpoints support policies - see the [relevant AWS documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-access.html) for more details.
     * 
     */
    public Optional<Output<String>> policy() {
        return Optional.ofNullable(this.policy);
    }

    /**
     * Whether or not to associate a private hosted zone with the specified VPC. Applicable for endpoints of type Interface. Defaults to `false`.
     * 
     */
    @Import(name="privateDnsEnabled")
    private @Nullable Boolean privateDnsEnabled;

    /**
     * @return Whether or not to associate a private hosted zone with the specified VPC. Applicable for endpoints of type Interface. Defaults to `false`.
     * 
     */
    public Optional<Boolean> privateDnsEnabled() {
        return Optional.ofNullable(this.privateDnsEnabled);
    }

    /**
     * Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
     * 
     */
    @Import(name="region")
    private @Nullable Output<String> region;

    /**
     * @return Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
     * 
     */
    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    /**
     * The ARN of a Resource Configuration to connect this VPC Endpoint to. Exactly one of &lt;span pulumi-lang-nodejs=&#34;`resourceConfigurationArn`&#34; pulumi-lang-dotnet=&#34;`ResourceConfigurationArn`&#34; pulumi-lang-go=&#34;`resourceConfigurationArn`&#34; pulumi-lang-python=&#34;`resource_configuration_arn`&#34; pulumi-lang-yaml=&#34;`resourceConfigurationArn`&#34; pulumi-lang-java=&#34;`resourceConfigurationArn`&#34;&gt;`resource_configuration_arn`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`serviceName`&#34; pulumi-lang-dotnet=&#34;`ServiceName`&#34; pulumi-lang-go=&#34;`serviceName`&#34; pulumi-lang-python=&#34;`service_name`&#34; pulumi-lang-yaml=&#34;`serviceName`&#34; pulumi-lang-java=&#34;`serviceName`&#34;&gt;`service_name`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`serviceNetworkArn`&#34; pulumi-lang-dotnet=&#34;`ServiceNetworkArn`&#34; pulumi-lang-go=&#34;`serviceNetworkArn`&#34; pulumi-lang-python=&#34;`service_network_arn`&#34; pulumi-lang-yaml=&#34;`serviceNetworkArn`&#34; pulumi-lang-java=&#34;`serviceNetworkArn`&#34;&gt;`service_network_arn`&lt;/span&gt; is required.
     * 
     */
    @Import(name="resourceConfigurationArn")
    private @Nullable Output<String> resourceConfigurationArn;

    /**
     * @return The ARN of a Resource Configuration to connect this VPC Endpoint to. Exactly one of &lt;span pulumi-lang-nodejs=&#34;`resourceConfigurationArn`&#34; pulumi-lang-dotnet=&#34;`ResourceConfigurationArn`&#34; pulumi-lang-go=&#34;`resourceConfigurationArn`&#34; pulumi-lang-python=&#34;`resource_configuration_arn`&#34; pulumi-lang-yaml=&#34;`resourceConfigurationArn`&#34; pulumi-lang-java=&#34;`resourceConfigurationArn`&#34;&gt;`resource_configuration_arn`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`serviceName`&#34; pulumi-lang-dotnet=&#34;`ServiceName`&#34; pulumi-lang-go=&#34;`serviceName`&#34; pulumi-lang-python=&#34;`service_name`&#34; pulumi-lang-yaml=&#34;`serviceName`&#34; pulumi-lang-java=&#34;`serviceName`&#34;&gt;`service_name`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`serviceNetworkArn`&#34; pulumi-lang-dotnet=&#34;`ServiceNetworkArn`&#34; pulumi-lang-go=&#34;`serviceNetworkArn`&#34; pulumi-lang-python=&#34;`service_network_arn`&#34; pulumi-lang-yaml=&#34;`serviceNetworkArn`&#34; pulumi-lang-java=&#34;`serviceNetworkArn`&#34;&gt;`service_network_arn`&lt;/span&gt; is required.
     * 
     */
    public Optional<Output<String>> resourceConfigurationArn() {
        return Optional.ofNullable(this.resourceConfigurationArn);
    }

    /**
     * One or more route table IDs. Applicable for endpoints of type `Gateway`.
     * 
     */
    @Import(name="routeTableIds")
    private @Nullable Output<List<String>> routeTableIds;

    /**
     * @return One or more route table IDs. Applicable for endpoints of type `Gateway`.
     * 
     */
    public Optional<Output<List<String>>> routeTableIds() {
        return Optional.ofNullable(this.routeTableIds);
    }

    /**
     * The ID of one or more security groups to associate with the network interface. Applicable for endpoints of type `Interface`.
     * If no security groups are specified, the VPC&#39;s [default security group](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#DefaultSecurityGroup) is associated with the endpoint.
     * 
     */
    @Import(name="securityGroupIds")
    private @Nullable Output<List<String>> securityGroupIds;

    /**
     * @return The ID of one or more security groups to associate with the network interface. Applicable for endpoints of type `Interface`.
     * If no security groups are specified, the VPC&#39;s [default security group](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#DefaultSecurityGroup) is associated with the endpoint.
     * 
     */
    public Optional<Output<List<String>>> securityGroupIds() {
        return Optional.ofNullable(this.securityGroupIds);
    }

    /**
     * The service name. For AWS services the service name is usually in the form `com.amazonaws.&lt;region&gt;.&lt;service&gt;` (the SageMaker Notebook service is an exception to this rule, the service name is in the form `aws.sagemaker.&lt;region&gt;.notebook`).
     * 
     */
    @Import(name="serviceName", required=true)
    private String serviceName;

    /**
     * @return The service name. For AWS services the service name is usually in the form `com.amazonaws.&lt;region&gt;.&lt;service&gt;` (the SageMaker Notebook service is an exception to this rule, the service name is in the form `aws.sagemaker.&lt;region&gt;.notebook`).
     * 
     */
    public String serviceName() {
        return this.serviceName;
    }

    /**
     * The ARN of a Service Network to connect this VPC Endpoint to. Exactly one of &lt;span pulumi-lang-nodejs=&#34;`resourceConfigurationArn`&#34; pulumi-lang-dotnet=&#34;`ResourceConfigurationArn`&#34; pulumi-lang-go=&#34;`resourceConfigurationArn`&#34; pulumi-lang-python=&#34;`resource_configuration_arn`&#34; pulumi-lang-yaml=&#34;`resourceConfigurationArn`&#34; pulumi-lang-java=&#34;`resourceConfigurationArn`&#34;&gt;`resource_configuration_arn`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`serviceName`&#34; pulumi-lang-dotnet=&#34;`ServiceName`&#34; pulumi-lang-go=&#34;`serviceName`&#34; pulumi-lang-python=&#34;`service_name`&#34; pulumi-lang-yaml=&#34;`serviceName`&#34; pulumi-lang-java=&#34;`serviceName`&#34;&gt;`service_name`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`serviceNetworkArn`&#34; pulumi-lang-dotnet=&#34;`ServiceNetworkArn`&#34; pulumi-lang-go=&#34;`serviceNetworkArn`&#34; pulumi-lang-python=&#34;`service_network_arn`&#34; pulumi-lang-yaml=&#34;`serviceNetworkArn`&#34; pulumi-lang-java=&#34;`serviceNetworkArn`&#34;&gt;`service_network_arn`&lt;/span&gt; is required.
     * 
     */
    @Import(name="serviceNetworkArn")
    private @Nullable Output<String> serviceNetworkArn;

    /**
     * @return The ARN of a Service Network to connect this VPC Endpoint to. Exactly one of &lt;span pulumi-lang-nodejs=&#34;`resourceConfigurationArn`&#34; pulumi-lang-dotnet=&#34;`ResourceConfigurationArn`&#34; pulumi-lang-go=&#34;`resourceConfigurationArn`&#34; pulumi-lang-python=&#34;`resource_configuration_arn`&#34; pulumi-lang-yaml=&#34;`resourceConfigurationArn`&#34; pulumi-lang-java=&#34;`resourceConfigurationArn`&#34;&gt;`resource_configuration_arn`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`serviceName`&#34; pulumi-lang-dotnet=&#34;`ServiceName`&#34; pulumi-lang-go=&#34;`serviceName`&#34; pulumi-lang-python=&#34;`service_name`&#34; pulumi-lang-yaml=&#34;`serviceName`&#34; pulumi-lang-java=&#34;`serviceName`&#34;&gt;`service_name`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`serviceNetworkArn`&#34; pulumi-lang-dotnet=&#34;`ServiceNetworkArn`&#34; pulumi-lang-go=&#34;`serviceNetworkArn`&#34; pulumi-lang-python=&#34;`service_network_arn`&#34; pulumi-lang-yaml=&#34;`serviceNetworkArn`&#34; pulumi-lang-java=&#34;`serviceNetworkArn`&#34;&gt;`service_network_arn`&lt;/span&gt; is required.
     * 
     */
    public Optional<Output<String>> serviceNetworkArn() {
        return Optional.ofNullable(this.serviceNetworkArn);
    }

    /**
     * The AWS region of the VPC Endpoint Service. If specified, the VPC endpoint will connect to the service in the provided region. Applicable for endpoints of type `Interface`.
     * 
     */
    @Import(name="serviceRegion")
    private @Nullable Output<String> serviceRegion;

    /**
     * @return The AWS region of the VPC Endpoint Service. If specified, the VPC endpoint will connect to the service in the provided region. Applicable for endpoints of type `Interface`.
     * 
     */
    public Optional<Output<String>> serviceRegion() {
        return Optional.ofNullable(this.serviceRegion);
    }

    /**
     * Subnet configuration for the endpoint, used to select specific IPv4 and/or IPv6 addresses to the endpoint. See&lt;span pulumi-lang-nodejs=&#34; subnetConfiguration &#34; pulumi-lang-dotnet=&#34; SubnetConfiguration &#34; pulumi-lang-go=&#34; subnetConfiguration &#34; pulumi-lang-python=&#34; subnet_configuration &#34; pulumi-lang-yaml=&#34; subnetConfiguration &#34; pulumi-lang-java=&#34; subnetConfiguration &#34;&gt; subnet_configuration &lt;/span&gt;below.
     * 
     */
    @Import(name="subnetConfigurations")
    private @Nullable Output<List<VpcEndpointSubnetConfigurationArgs>> subnetConfigurations;

    /**
     * @return Subnet configuration for the endpoint, used to select specific IPv4 and/or IPv6 addresses to the endpoint. See&lt;span pulumi-lang-nodejs=&#34; subnetConfiguration &#34; pulumi-lang-dotnet=&#34; SubnetConfiguration &#34; pulumi-lang-go=&#34; subnetConfiguration &#34; pulumi-lang-python=&#34; subnet_configuration &#34; pulumi-lang-yaml=&#34; subnetConfiguration &#34; pulumi-lang-java=&#34; subnetConfiguration &#34;&gt; subnet_configuration &lt;/span&gt;below.
     * 
     */
    public Optional<Output<List<VpcEndpointSubnetConfigurationArgs>>> subnetConfigurations() {
        return Optional.ofNullable(this.subnetConfigurations);
    }

    /**
     * The ID of one or more subnets in which to create a network interface for the endpoint. Applicable for endpoints of type `GatewayLoadBalancer` and `Interface`. Interface type endpoints cannot function without being assigned to a subnet.
     * 
     */
    @Import(name="subnetIds")
    private @Nullable Output<List<String>> subnetIds;

    /**
     * @return The ID of one or more subnets in which to create a network interface for the endpoint. Applicable for endpoints of type `GatewayLoadBalancer` and `Interface`. Interface type endpoints cannot function without being assigned to a subnet.
     * 
     */
    public Optional<Output<List<String>>> subnetIds() {
        return Optional.ofNullable(this.subnetIds);
    }

    /**
     * A map of tags to assign to the resource. If configured with a provider &lt;span pulumi-lang-nodejs=&#34;`defaultTags`&#34; pulumi-lang-dotnet=&#34;`DefaultTags`&#34; pulumi-lang-go=&#34;`defaultTags`&#34; pulumi-lang-python=&#34;`default_tags`&#34; pulumi-lang-yaml=&#34;`defaultTags`&#34; pulumi-lang-java=&#34;`defaultTags`&#34;&gt;`default_tags`&lt;/span&gt; configuration block present, tags with matching keys will overwrite those defined at the provider-level.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<Map<String,String>> tags;

    /**
     * @return A map of tags to assign to the resource. If configured with a provider &lt;span pulumi-lang-nodejs=&#34;`defaultTags`&#34; pulumi-lang-dotnet=&#34;`DefaultTags`&#34; pulumi-lang-go=&#34;`defaultTags`&#34; pulumi-lang-python=&#34;`default_tags`&#34; pulumi-lang-yaml=&#34;`defaultTags`&#34; pulumi-lang-java=&#34;`defaultTags`&#34;&gt;`default_tags`&lt;/span&gt; configuration block present, tags with matching keys will overwrite those defined at the provider-level.
     * 
     */
    public Optional<Output<Map<String,String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    /**
     * The VPC endpoint type, `Gateway`, `GatewayLoadBalancer`,`Interface`, `Resource` or `ServiceNetwork`. Defaults to `Gateway`.
     * 
     */
    @Import(name="vpcEndpointType")
    private @Nullable Output<String> vpcEndpointType;

    /**
     * @return The VPC endpoint type, `Gateway`, `GatewayLoadBalancer`,`Interface`, `Resource` or `ServiceNetwork`. Defaults to `Gateway`.
     * 
     */
    public Optional<Output<String>> vpcEndpointType() {
        return Optional.ofNullable(this.vpcEndpointType);
    }

    private VpcEndpointSpecArgs() {}

    private VpcEndpointSpecArgs(VpcEndpointSpecArgs $) {
        this.autoAccept = $.autoAccept;
        this.dnsOptions = $.dnsOptions;
        this.ipAddressType = $.ipAddressType;
        this.policy = $.policy;
        this.privateDnsEnabled = $.privateDnsEnabled;
        this.region = $.region;
        this.resourceConfigurationArn = $.resourceConfigurationArn;
        this.routeTableIds = $.routeTableIds;
        this.securityGroupIds = $.securityGroupIds;
        this.serviceName = $.serviceName;
        this.serviceNetworkArn = $.serviceNetworkArn;
        this.serviceRegion = $.serviceRegion;
        this.subnetConfigurations = $.subnetConfigurations;
        this.subnetIds = $.subnetIds;
        this.tags = $.tags;
        this.vpcEndpointType = $.vpcEndpointType;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VpcEndpointSpecArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VpcEndpointSpecArgs $;

        public Builder() {
            $ = new VpcEndpointSpecArgs();
        }

        public Builder(VpcEndpointSpecArgs defaults) {
            $ = new VpcEndpointSpecArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param autoAccept Accept the VPC endpoint (the VPC endpoint and service need to be in the same AWS account).
         * 
         * @return builder
         * 
         */
        public Builder autoAccept(@Nullable Boolean autoAccept) {
            $.autoAccept = autoAccept;
            return this;
        }

        /**
         * @param dnsOptions The DNS options for the endpoint. See&lt;span pulumi-lang-nodejs=&#34; dnsOptions &#34; pulumi-lang-dotnet=&#34; DnsOptions &#34; pulumi-lang-go=&#34; dnsOptions &#34; pulumi-lang-python=&#34; dns_options &#34; pulumi-lang-yaml=&#34; dnsOptions &#34; pulumi-lang-java=&#34; dnsOptions &#34;&gt; dns_options &lt;/span&gt;below.
         * 
         * @return builder
         * 
         */
        public Builder dnsOptions(@Nullable Output<VpcEndpointDnsOptionsArgs> dnsOptions) {
            $.dnsOptions = dnsOptions;
            return this;
        }

        /**
         * @param dnsOptions The DNS options for the endpoint. See&lt;span pulumi-lang-nodejs=&#34; dnsOptions &#34; pulumi-lang-dotnet=&#34; DnsOptions &#34; pulumi-lang-go=&#34; dnsOptions &#34; pulumi-lang-python=&#34; dns_options &#34; pulumi-lang-yaml=&#34; dnsOptions &#34; pulumi-lang-java=&#34; dnsOptions &#34;&gt; dns_options &lt;/span&gt;below.
         * 
         * @return builder
         * 
         */
        public Builder dnsOptions(VpcEndpointDnsOptionsArgs dnsOptions) {
            return dnsOptions(Output.of(dnsOptions));
        }

        /**
         * @param ipAddressType The IP address type for the endpoint. Valid values are &lt;span pulumi-lang-nodejs=&#34;`ipv4`&#34; pulumi-lang-dotnet=&#34;`Ipv4`&#34; pulumi-lang-go=&#34;`ipv4`&#34; pulumi-lang-python=&#34;`ipv4`&#34; pulumi-lang-yaml=&#34;`ipv4`&#34; pulumi-lang-java=&#34;`ipv4`&#34;&gt;`ipv4`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`dualstack`&#34; pulumi-lang-dotnet=&#34;`Dualstack`&#34; pulumi-lang-go=&#34;`dualstack`&#34; pulumi-lang-python=&#34;`dualstack`&#34; pulumi-lang-yaml=&#34;`dualstack`&#34; pulumi-lang-java=&#34;`dualstack`&#34;&gt;`dualstack`&lt;/span&gt;, and &lt;span pulumi-lang-nodejs=&#34;`ipv6`&#34; pulumi-lang-dotnet=&#34;`Ipv6`&#34; pulumi-lang-go=&#34;`ipv6`&#34; pulumi-lang-python=&#34;`ipv6`&#34; pulumi-lang-yaml=&#34;`ipv6`&#34; pulumi-lang-java=&#34;`ipv6`&#34;&gt;`ipv6`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder ipAddressType(@Nullable Output<String> ipAddressType) {
            $.ipAddressType = ipAddressType;
            return this;
        }

        /**
         * @param ipAddressType The IP address type for the endpoint. Valid values are &lt;span pulumi-lang-nodejs=&#34;`ipv4`&#34; pulumi-lang-dotnet=&#34;`Ipv4`&#34; pulumi-lang-go=&#34;`ipv4`&#34; pulumi-lang-python=&#34;`ipv4`&#34; pulumi-lang-yaml=&#34;`ipv4`&#34; pulumi-lang-java=&#34;`ipv4`&#34;&gt;`ipv4`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`dualstack`&#34; pulumi-lang-dotnet=&#34;`Dualstack`&#34; pulumi-lang-go=&#34;`dualstack`&#34; pulumi-lang-python=&#34;`dualstack`&#34; pulumi-lang-yaml=&#34;`dualstack`&#34; pulumi-lang-java=&#34;`dualstack`&#34;&gt;`dualstack`&lt;/span&gt;, and &lt;span pulumi-lang-nodejs=&#34;`ipv6`&#34; pulumi-lang-dotnet=&#34;`Ipv6`&#34; pulumi-lang-go=&#34;`ipv6`&#34; pulumi-lang-python=&#34;`ipv6`&#34; pulumi-lang-yaml=&#34;`ipv6`&#34; pulumi-lang-java=&#34;`ipv6`&#34;&gt;`ipv6`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder ipAddressType(String ipAddressType) {
            return ipAddressType(Output.of(ipAddressType));
        }

        /**
         * @param policy A policy to attach to the endpoint that controls access to the service. This is a JSON formatted string. Defaults to full access. All `Gateway` and some `Interface` endpoints support policies - see the [relevant AWS documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-access.html) for more details.
         * 
         * @return builder
         * 
         */
        public Builder policy(@Nullable Output<String> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy A policy to attach to the endpoint that controls access to the service. This is a JSON formatted string. Defaults to full access. All `Gateway` and some `Interface` endpoints support policies - see the [relevant AWS documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-access.html) for more details.
         * 
         * @return builder
         * 
         */
        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        /**
         * @param privateDnsEnabled Whether or not to associate a private hosted zone with the specified VPC. Applicable for endpoints of type Interface. Defaults to `false`.
         * 
         * @return builder
         * 
         */
        public Builder privateDnsEnabled(@Nullable Boolean privateDnsEnabled) {
            $.privateDnsEnabled = privateDnsEnabled;
            return this;
        }

        /**
         * @param region Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region Region where this resource will be [managed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints). Defaults to the Region set in the provider configuration.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param resourceConfigurationArn The ARN of a Resource Configuration to connect this VPC Endpoint to. Exactly one of &lt;span pulumi-lang-nodejs=&#34;`resourceConfigurationArn`&#34; pulumi-lang-dotnet=&#34;`ResourceConfigurationArn`&#34; pulumi-lang-go=&#34;`resourceConfigurationArn`&#34; pulumi-lang-python=&#34;`resource_configuration_arn`&#34; pulumi-lang-yaml=&#34;`resourceConfigurationArn`&#34; pulumi-lang-java=&#34;`resourceConfigurationArn`&#34;&gt;`resource_configuration_arn`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`serviceName`&#34; pulumi-lang-dotnet=&#34;`ServiceName`&#34; pulumi-lang-go=&#34;`serviceName`&#34; pulumi-lang-python=&#34;`service_name`&#34; pulumi-lang-yaml=&#34;`serviceName`&#34; pulumi-lang-java=&#34;`serviceName`&#34;&gt;`service_name`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`serviceNetworkArn`&#34; pulumi-lang-dotnet=&#34;`ServiceNetworkArn`&#34; pulumi-lang-go=&#34;`serviceNetworkArn`&#34; pulumi-lang-python=&#34;`service_network_arn`&#34; pulumi-lang-yaml=&#34;`serviceNetworkArn`&#34; pulumi-lang-java=&#34;`serviceNetworkArn`&#34;&gt;`service_network_arn`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder resourceConfigurationArn(@Nullable Output<String> resourceConfigurationArn) {
            $.resourceConfigurationArn = resourceConfigurationArn;
            return this;
        }

        /**
         * @param resourceConfigurationArn The ARN of a Resource Configuration to connect this VPC Endpoint to. Exactly one of &lt;span pulumi-lang-nodejs=&#34;`resourceConfigurationArn`&#34; pulumi-lang-dotnet=&#34;`ResourceConfigurationArn`&#34; pulumi-lang-go=&#34;`resourceConfigurationArn`&#34; pulumi-lang-python=&#34;`resource_configuration_arn`&#34; pulumi-lang-yaml=&#34;`resourceConfigurationArn`&#34; pulumi-lang-java=&#34;`resourceConfigurationArn`&#34;&gt;`resource_configuration_arn`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`serviceName`&#34; pulumi-lang-dotnet=&#34;`ServiceName`&#34; pulumi-lang-go=&#34;`serviceName`&#34; pulumi-lang-python=&#34;`service_name`&#34; pulumi-lang-yaml=&#34;`serviceName`&#34; pulumi-lang-java=&#34;`serviceName`&#34;&gt;`service_name`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`serviceNetworkArn`&#34; pulumi-lang-dotnet=&#34;`ServiceNetworkArn`&#34; pulumi-lang-go=&#34;`serviceNetworkArn`&#34; pulumi-lang-python=&#34;`service_network_arn`&#34; pulumi-lang-yaml=&#34;`serviceNetworkArn`&#34; pulumi-lang-java=&#34;`serviceNetworkArn`&#34;&gt;`service_network_arn`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder resourceConfigurationArn(String resourceConfigurationArn) {
            return resourceConfigurationArn(Output.of(resourceConfigurationArn));
        }

        /**
         * @param routeTableIds One or more route table IDs. Applicable for endpoints of type `Gateway`.
         * 
         * @return builder
         * 
         */
        public Builder routeTableIds(@Nullable Output<List<String>> routeTableIds) {
            $.routeTableIds = routeTableIds;
            return this;
        }

        /**
         * @param routeTableIds One or more route table IDs. Applicable for endpoints of type `Gateway`.
         * 
         * @return builder
         * 
         */
        public Builder routeTableIds(List<String> routeTableIds) {
            return routeTableIds(Output.of(routeTableIds));
        }

        /**
         * @param routeTableIds One or more route table IDs. Applicable for endpoints of type `Gateway`.
         * 
         * @return builder
         * 
         */
        public Builder routeTableIds(String... routeTableIds) {
            return routeTableIds(List.of(routeTableIds));
        }

        /**
         * @param securityGroupIds The ID of one or more security groups to associate with the network interface. Applicable for endpoints of type `Interface`.
         * If no security groups are specified, the VPC&#39;s [default security group](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#DefaultSecurityGroup) is associated with the endpoint.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(@Nullable Output<List<String>> securityGroupIds) {
            $.securityGroupIds = securityGroupIds;
            return this;
        }

        /**
         * @param securityGroupIds The ID of one or more security groups to associate with the network interface. Applicable for endpoints of type `Interface`.
         * If no security groups are specified, the VPC&#39;s [default security group](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#DefaultSecurityGroup) is associated with the endpoint.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(List<String> securityGroupIds) {
            return securityGroupIds(Output.of(securityGroupIds));
        }

        /**
         * @param securityGroupIds The ID of one or more security groups to associate with the network interface. Applicable for endpoints of type `Interface`.
         * If no security groups are specified, the VPC&#39;s [default security group](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#DefaultSecurityGroup) is associated with the endpoint.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupIds(String... securityGroupIds) {
            return securityGroupIds(List.of(securityGroupIds));
        }

        /**
         * @param serviceName The service name. For AWS services the service name is usually in the form `com.amazonaws.&lt;region&gt;.&lt;service&gt;` (the SageMaker Notebook service is an exception to this rule, the service name is in the form `aws.sagemaker.&lt;region&gt;.notebook`).
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        /**
         * @param serviceNetworkArn The ARN of a Service Network to connect this VPC Endpoint to. Exactly one of &lt;span pulumi-lang-nodejs=&#34;`resourceConfigurationArn`&#34; pulumi-lang-dotnet=&#34;`ResourceConfigurationArn`&#34; pulumi-lang-go=&#34;`resourceConfigurationArn`&#34; pulumi-lang-python=&#34;`resource_configuration_arn`&#34; pulumi-lang-yaml=&#34;`resourceConfigurationArn`&#34; pulumi-lang-java=&#34;`resourceConfigurationArn`&#34;&gt;`resource_configuration_arn`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`serviceName`&#34; pulumi-lang-dotnet=&#34;`ServiceName`&#34; pulumi-lang-go=&#34;`serviceName`&#34; pulumi-lang-python=&#34;`service_name`&#34; pulumi-lang-yaml=&#34;`serviceName`&#34; pulumi-lang-java=&#34;`serviceName`&#34;&gt;`service_name`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`serviceNetworkArn`&#34; pulumi-lang-dotnet=&#34;`ServiceNetworkArn`&#34; pulumi-lang-go=&#34;`serviceNetworkArn`&#34; pulumi-lang-python=&#34;`service_network_arn`&#34; pulumi-lang-yaml=&#34;`serviceNetworkArn`&#34; pulumi-lang-java=&#34;`serviceNetworkArn`&#34;&gt;`service_network_arn`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder serviceNetworkArn(@Nullable Output<String> serviceNetworkArn) {
            $.serviceNetworkArn = serviceNetworkArn;
            return this;
        }

        /**
         * @param serviceNetworkArn The ARN of a Service Network to connect this VPC Endpoint to. Exactly one of &lt;span pulumi-lang-nodejs=&#34;`resourceConfigurationArn`&#34; pulumi-lang-dotnet=&#34;`ResourceConfigurationArn`&#34; pulumi-lang-go=&#34;`resourceConfigurationArn`&#34; pulumi-lang-python=&#34;`resource_configuration_arn`&#34; pulumi-lang-yaml=&#34;`resourceConfigurationArn`&#34; pulumi-lang-java=&#34;`resourceConfigurationArn`&#34;&gt;`resource_configuration_arn`&lt;/span&gt;, &lt;span pulumi-lang-nodejs=&#34;`serviceName`&#34; pulumi-lang-dotnet=&#34;`ServiceName`&#34; pulumi-lang-go=&#34;`serviceName`&#34; pulumi-lang-python=&#34;`service_name`&#34; pulumi-lang-yaml=&#34;`serviceName`&#34; pulumi-lang-java=&#34;`serviceName`&#34;&gt;`service_name`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`serviceNetworkArn`&#34; pulumi-lang-dotnet=&#34;`ServiceNetworkArn`&#34; pulumi-lang-go=&#34;`serviceNetworkArn`&#34; pulumi-lang-python=&#34;`service_network_arn`&#34; pulumi-lang-yaml=&#34;`serviceNetworkArn`&#34; pulumi-lang-java=&#34;`serviceNetworkArn`&#34;&gt;`service_network_arn`&lt;/span&gt; is required.
         * 
         * @return builder
         * 
         */
        public Builder serviceNetworkArn(String serviceNetworkArn) {
            return serviceNetworkArn(Output.of(serviceNetworkArn));
        }

        /**
         * @param serviceRegion The AWS region of the VPC Endpoint Service. If specified, the VPC endpoint will connect to the service in the provided region. Applicable for endpoints of type `Interface`.
         * 
         * @return builder
         * 
         */
        public Builder serviceRegion(@Nullable Output<String> serviceRegion) {
            $.serviceRegion = serviceRegion;
            return this;
        }

        /**
         * @param serviceRegion The AWS region of the VPC Endpoint Service. If specified, the VPC endpoint will connect to the service in the provided region. Applicable for endpoints of type `Interface`.
         * 
         * @return builder
         * 
         */
        public Builder serviceRegion(String serviceRegion) {
            return serviceRegion(Output.of(serviceRegion));
        }

        /**
         * @param subnetConfigurations Subnet configuration for the endpoint, used to select specific IPv4 and/or IPv6 addresses to the endpoint. See&lt;span pulumi-lang-nodejs=&#34; subnetConfiguration &#34; pulumi-lang-dotnet=&#34; SubnetConfiguration &#34; pulumi-lang-go=&#34; subnetConfiguration &#34; pulumi-lang-python=&#34; subnet_configuration &#34; pulumi-lang-yaml=&#34; subnetConfiguration &#34; pulumi-lang-java=&#34; subnetConfiguration &#34;&gt; subnet_configuration &lt;/span&gt;below.
         * 
         * @return builder
         * 
         */
        public Builder subnetConfigurations(@Nullable Output<List<VpcEndpointSubnetConfigurationArgs>> subnetConfigurations) {
            $.subnetConfigurations = subnetConfigurations;
            return this;
        }

        /**
         * @param subnetConfigurations Subnet configuration for the endpoint, used to select specific IPv4 and/or IPv6 addresses to the endpoint. See&lt;span pulumi-lang-nodejs=&#34; subnetConfiguration &#34; pulumi-lang-dotnet=&#34; SubnetConfiguration &#34; pulumi-lang-go=&#34; subnetConfiguration &#34; pulumi-lang-python=&#34; subnet_configuration &#34; pulumi-lang-yaml=&#34; subnetConfiguration &#34; pulumi-lang-java=&#34; subnetConfiguration &#34;&gt; subnet_configuration &lt;/span&gt;below.
         * 
         * @return builder
         * 
         */
        public Builder subnetConfigurations(List<VpcEndpointSubnetConfigurationArgs> subnetConfigurations) {
            return subnetConfigurations(Output.of(subnetConfigurations));
        }

        /**
         * @param subnetConfigurations Subnet configuration for the endpoint, used to select specific IPv4 and/or IPv6 addresses to the endpoint. See&lt;span pulumi-lang-nodejs=&#34; subnetConfiguration &#34; pulumi-lang-dotnet=&#34; SubnetConfiguration &#34; pulumi-lang-go=&#34; subnetConfiguration &#34; pulumi-lang-python=&#34; subnet_configuration &#34; pulumi-lang-yaml=&#34; subnetConfiguration &#34; pulumi-lang-java=&#34; subnetConfiguration &#34;&gt; subnet_configuration &lt;/span&gt;below.
         * 
         * @return builder
         * 
         */
        public Builder subnetConfigurations(VpcEndpointSubnetConfigurationArgs... subnetConfigurations) {
            return subnetConfigurations(List.of(subnetConfigurations));
        }

        /**
         * @param subnetIds The ID of one or more subnets in which to create a network interface for the endpoint. Applicable for endpoints of type `GatewayLoadBalancer` and `Interface`. Interface type endpoints cannot function without being assigned to a subnet.
         * 
         * @return builder
         * 
         */
        public Builder subnetIds(@Nullable Output<List<String>> subnetIds) {
            $.subnetIds = subnetIds;
            return this;
        }

        /**
         * @param subnetIds The ID of one or more subnets in which to create a network interface for the endpoint. Applicable for endpoints of type `GatewayLoadBalancer` and `Interface`. Interface type endpoints cannot function without being assigned to a subnet.
         * 
         * @return builder
         * 
         */
        public Builder subnetIds(List<String> subnetIds) {
            return subnetIds(Output.of(subnetIds));
        }

        /**
         * @param subnetIds The ID of one or more subnets in which to create a network interface for the endpoint. Applicable for endpoints of type `GatewayLoadBalancer` and `Interface`. Interface type endpoints cannot function without being assigned to a subnet.
         * 
         * @return builder
         * 
         */
        public Builder subnetIds(String... subnetIds) {
            return subnetIds(List.of(subnetIds));
        }

        /**
         * @param tags A map of tags to assign to the resource. If configured with a provider &lt;span pulumi-lang-nodejs=&#34;`defaultTags`&#34; pulumi-lang-dotnet=&#34;`DefaultTags`&#34; pulumi-lang-go=&#34;`defaultTags`&#34; pulumi-lang-python=&#34;`default_tags`&#34; pulumi-lang-yaml=&#34;`defaultTags`&#34; pulumi-lang-java=&#34;`defaultTags`&#34;&gt;`default_tags`&lt;/span&gt; configuration block present, tags with matching keys will overwrite those defined at the provider-level.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<Map<String,String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags A map of tags to assign to the resource. If configured with a provider &lt;span pulumi-lang-nodejs=&#34;`defaultTags`&#34; pulumi-lang-dotnet=&#34;`DefaultTags`&#34; pulumi-lang-go=&#34;`defaultTags`&#34; pulumi-lang-python=&#34;`default_tags`&#34; pulumi-lang-yaml=&#34;`defaultTags`&#34; pulumi-lang-java=&#34;`defaultTags`&#34;&gt;`default_tags`&lt;/span&gt; configuration block present, tags with matching keys will overwrite those defined at the provider-level.
         * 
         * @return builder
         * 
         */
        public Builder tags(Map<String,String> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param vpcEndpointType The VPC endpoint type, `Gateway`, `GatewayLoadBalancer`,`Interface`, `Resource` or `ServiceNetwork`. Defaults to `Gateway`.
         * 
         * @return builder
         * 
         */
        public Builder vpcEndpointType(@Nullable Output<String> vpcEndpointType) {
            $.vpcEndpointType = vpcEndpointType;
            return this;
        }

        /**
         * @param vpcEndpointType The VPC endpoint type, `Gateway`, `GatewayLoadBalancer`,`Interface`, `Resource` or `ServiceNetwork`. Defaults to `Gateway`.
         * 
         * @return builder
         * 
         */
        public Builder vpcEndpointType(String vpcEndpointType) {
            return vpcEndpointType(Output.of(vpcEndpointType));
        }

        public VpcEndpointSpecArgs build() {
            if ($.serviceName == null) {
                throw new MissingRequiredPropertyException("VpcEndpointSpecArgs", "serviceName");
            }
            return $;
        }
    }

}
