// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsx.experimental_cloudwatch.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class LogGroupReference {
    private String arn;
    private String name;
    private String region;

    private LogGroupReference() {}
    public String arn() {
        return this.arn;
    }
    public String name() {
        return this.name;
    }
    public String region() {
        return this.region;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogGroupReference defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String arn;
        private String name;
        private String region;
        public Builder() {}
        public Builder(LogGroupReference defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.arn = defaults.arn;
    	      this.name = defaults.name;
    	      this.region = defaults.region;
        }

        @CustomType.Setter
        public Builder arn(String arn) {
            if (arn == null) {
              throw new MissingRequiredPropertyException("LogGroupReference", "arn");
            }
            this.arn = arn;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("LogGroupReference", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder region(String region) {
            if (region == null) {
              throw new MissingRequiredPropertyException("LogGroupReference", "region");
            }
            this.region = region;
            return this;
        }
        public LogGroupReference build() {
            final var _resultValue = new LogGroupReference();
            _resultValue.arn = arn;
            _resultValue.name = name;
            _resultValue.region = region;
            return _resultValue;
        }
    }
}
