// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsx.Lb.Inputs
{

    /// <summary>
    /// Target Group with default setup unless explicitly skipped or an existing security group id provided.
    /// </summary>
    public sealed class DefaultTargetGroupArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Args to use when creating the target group. Can't be specified if [targetGroupArn] is used.
        /// </summary>
        [Input("args")]
        public Inputs.TargetGroupArgs? Args { get; set; }

        /// <summary>
        /// Skips creation of the target group if set to `true`.
        /// </summary>
        [Input("skip")]
        public bool? Skip { get; set; }

        /// <summary>
        /// ARN of existing target group to use instead of creating a new target group. Cannot be used in combination with [args].
        /// </summary>
        [Input("targetGroupArn")]
        public Input<string>? TargetGroupArn { get; set; }

        public DefaultTargetGroupArgs()
        {
        }
    }
}
