// *** WARNING: this file was generated by pulumi-gen-awsx. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const TaskDefinitionPortMappingAppProtocol = {
    Http: "http",
    Http2: "http2",
    Grpc: "grpc",
} as const;

export type TaskDefinitionPortMappingAppProtocol = (typeof TaskDefinitionPortMappingAppProtocol)[keyof typeof TaskDefinitionPortMappingAppProtocol];
