name: Command Dispatch for testing
on:
  issue_comment:
    types: [created, edited]

jobs:
  command-dispatch-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Build
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            run-acceptance-tests
            run-pulumi-update
          permission: write
          issue-type: pull-request
          repository: pulumi/pulumi-awsx
