name: version

on:
  workflow_call:
    outputs:
      version:
        description: Calculated version
        value: ${{ jobs.version.outputs.version }}

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

jobs:
  version:
    runs-on: ubuntu-latest
    name: Calculate Dev Version
    steps:
      - id: version
        name: Calculate build version
        uses: pulumi/provider-version-action@7c54f136703646f7d6eaa3d3b3c877e5a805d6ab # v1
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
